### PR TITLE
Deprecate `secrets`

### PR DESCRIPTION
**Pull request by qwerty287**
Deprecate the `secrets` directive completely.

Closes https://github.com/woodpecker-ci/woodpecker/discussions/4015

### CODE REVIEW

**Comment by zc-devs** [comment]
> replaces and closes https://github.com/woodpecker-ci/woodpecker/pull/4218

Are you going to backport this PR?

Anyway, it is not a replacement, because it says "in 3.0 you can still use `secrets`, but in 4.0 it will be removed".
And in my PR I warn people "you use lower-cased secret, which currently upper-cased; it won't be in 3.0, therefore those steps will fail (very?) likely". Which technically is not `changed pipeline syntax`, but result is the same from user's point of view.

**Comment by zc-devs** [comment]
> Which technically is not changed pipeline syntax, but result is the same from user's point of view.

So, you could just remove it in 3.0
https://github.com/woodpecker-ci/woodpecker/issues/3960#issuecomment-2395481872

**Comment by pat-s** [comment]
> So, you could just remove secrets in 3.0 and warn in 2.7.

If you mean 2.7.2 etc: I think many users are sticking with 2.7.0 due to the breaking changes in 2.7.1+, so they won't ever see warnings in 2.7.2.

**Comment by zc-devs** [comment]
> If you mean 2.7.2

Yep

> many users are sticking with 2.7.0 due to the breaking changes in 2.7.1+, so they won't ever see warnings in 2.7.2

Sad

> I'd also rather deprecate in v3 and remove in v4

Sure, it was just thing to consider.

**Review by lafriks — APPROVED** [review]

**Pull request merged**
