### PR TITLE
Header and Tabs UI Improvements

### PR DESCRIPTION
**Pull request by dvjn**
Some improvements to the Page Header and Tab UI.

Original |  New
:--------:|:-------:
image | image
image | image
image | image
image | image
image | image

What?
- Create a new Scaffold component, which includes the header and tabs required for a page.
- Use this component to wrap all the views that have a header.

Why?
- Ensures consistency in headers between different pages.
- (Opinion) Looks better than the current headers.

TODO:
- [x] Add support to use custom html/component in place of title (for repo page, pipeline page, etc)
- [x] Add support of right icon buttons (for repo page, pipeline page, etc)
- [x] Refactor tabs handling using compositions (useTabsProvider, useTabsClient)
- [x] Make new header ui resposive

### CODE REVIEW

**Comment by dvjn** [comment]
@6543 @qwerty287 @anbraten (or any other maintainer) could you review the visual changes / code changes, while I implement the rest of the changes?

My first time using vue :)

**Comment by dvjn** [comment]
Can anyone please review this?

Thanks!

**Comment by dvjn** [comment]
Any updates?

**Comment by lafriks** [comment]
New search looks a bit too unreadable (background/foreground contrast)

**Comment by dvjn** [comment]
@lafriks done :)

Before:
image

After:
image

**Comment by 6543** [comment]
I'll trust you so I'll merge

**Comment by 6543** [comment]
;)

**Pull request merged**
