### PR TITLE
PipelineLog.vue: Link lines to anchors

### PR DESCRIPTION
**Pull request by runephilosof-karnovgroup**
Sadly, the app currently does not scroll to element. It should also highlight it.
Extra points for making it possible to select and link to multiple lines

### CODE REVIEW

**Comment by runephilosof-karnovgroup** [comment]
It now scrolls to and highlights the selected line.
The highlighting could probably look better, feel free to improve on it.
Screenshot showing the highlighting:
Screenshot from 2023-06-27 11-48-35

**Comment by runephilosof-karnovgroup** [comment]
It seems the link and highlighting was implement in #1874.
However, it was done with a different ID. I think the ID attribute should be the same as the displayed line number.
And I assume it does not scroll to the line, since I needed to add some javascript to do that.

**Comment by runephilosof-karnovgroup** [comment]
@anbraten What do you think of these changes to the view you just touched?

**Comment by anbraten** [comment]
Looks great from the code. If you can confirm that the scrolling part works fine its can be merged from my side.

**Review by anbraten — APPROVED** [review]

**Comment by runephilosof-karnovgroup** [comment]
The merge conflict handling was not good. I am creating a follow up

**Pull request merged**
