### PR TITLE
Update pipeline steps and logs background

### PR DESCRIPTION
**Pull request by dvjn**
Why?
- Better contrast
- Looks modern

**Original** | **New**
:--------:|:-------:
image | image

### CODE REVIEW

**Review by lafriks — APPROVED** [review]

**Review by 6543 — CHANGES_REQUESTED** [review]
I like the old one, the new one do have to less contrast so you dont see the different elements difided anymore

**Comment by 6543** [comment]
yes you have more contrast for text but you loose the other one :/

**Comment by 6543** [comment]
image

if we go light with the elements, we might go dark with the background ...

**Comment by 6543** [comment]
197409473-4b97a2b8-a220-4019-ab33-abd2407d590a
?

-> the greay is just to demonstrate it ... but there should be better colors

**Comment by dvjn** [comment]
I've increased the shadow to match all the other cards in the UI.

If contrast between the card and background is still lacking, it will call for a bigger change on all the views and cards, and should be a separate issue/pr.

**Comment by dvjn** [comment]
New Screenshot:
image

**Review by 6543 — APPROVED** [review]
thanks - good work

**Comment by 6543** [comment]
> If contrast between the card and background is still lacking, it will call for a bigger change on all the views and cards, and should be a separate issue/pr.

yes we should do that

**Pull request merged**
