### PR TITLE
Fix en.json file syntax

### PR DESCRIPTION
**Pull request by lafriks**
<p>Weblate could not parse the translation files while updating the translations.</p>

<p>The following occurrences were found:</p>

Filename | Error
-- | --
web/src/assets/locales/en.json | JSONDecodeError('Expecting property name enclosed in double quotes: line 445 column 11 (char 18857)')
web/src/assets/locales/en.json | JSONDecodeError('Expecting property name enclosed in double quotes: line 445 column 11 (char 18857)')

### CODE REVIEW

**Review by 6543 — APPROVED** [review]

**Comment by 6543** [comment]
do we not have a linter for this file in place :/

**Comment by lafriks** [comment]
looks like we don't have :)

**Comment by 6543** [comment]
I'll create a stepbfor it ...

**Comment by 6543** [comment]
#2107 also do fix this

**Comment by 6543** [comment]
#2108 also do fix this

**Pull request merged**
