### PR TITLE
Add rolling semver tags, remove `latest` tag

### LINKED ISSUE #3131: Docker Tag vX.X not working
### Component

other

### Describe the bug

The docker tag `vX.X` (v2.1) (details: https://woodpecker-ci.org/docs/administration/deployment/docker-compose#docker-images) does not work.

### Additional context
```
docker pull woodpeckerci/woodpecker-server:v2.1-alpne
Error response from daemon: manifest for woodpeckerci/woodpecker-server:v2.1-alpne not found: manifest unknown: manifest unknown
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

### LINKED ISSUE #4597: Unexpected non-stable version for docker image woodpeckerci/woodpecker-server
### Component

server

### Describe the bug

I used auto update with the docker image "woodpeckerci/woodpecker-server:latest". A few days ago I got the Woodpecker 3.0.0.rc Version. I would have expected that under this tag there will be only stable versions. There is a tag next where I would expect the development version.

### Steps to reproduce

1. Pull and start the woodpeckerci/woodpecker-server:latest image

### Expected behavior

I would not expect to get a RC version under the latest tag. The RC version might belong under the next tag.

### System Info

```shell
N/A
```

### Additional context

_No response_

### Validations

- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]

### PR DESCRIPTION
**Pull request by pat-s**
fix #4597 fix #3131

- Removing `latest` tag to avoid automatic major release upgrades
- Add rolling tags for major and minor release versions (allows semi-automated upgrads and prevents from direct major upgrades)

### CODE REVIEW

**Comment by pat-s** [comment]
Oh dear, good point 🙈️

Changed it to the following

```sh
CI_COMMIT_TAG="v2.10.0"
short_tag=${CI_COMMIT_TAG%.*}
echo "$short_tag"
```

**Comment by anbraten** [comment]
`3.0.0.rc.0` and other rc versions would still override major versions as explained in #4597.
Can't get why we need to drop `latest`. We could suggest people to use pinned version, if they want to use `latest` fine.

**Comment by pat-s** [comment]
> 3.0.0.rc.0 and other rc versions would still override major versions as explained in https://github.com/woodpecker-ci/woodpecker/issues/4597.

Sure but in this case users opted in to use this version *on purpose* and not by getting a background update due to a rolling tag.

> Can't get why we need to drop latest. We could suggest people to use pinned version, if they want to use latest fine.

Even though some/most might do, the "a major upgrade happened and everything broke" issues will never stop this way, also because people often don't set a tag at all.
By removing `latest`, you workaround this problem actively by forcing users to specify a tag they want.

If you think about it, why should there ever be a tag crossing major version automatically? This will always result in a functional disaster. Admins have to adjust the config anyhow for a major upgrade, so arguing with "it reduces admin work" doesn't work. But it pro-actively prevents issues for admins and issues posted to the project. Does that make sense?

**Comment by IamIpanda** [comment]
> people often don't set a tag at all and hence will get latest implicitly.

That's reasonable, so may I know why `latest-alpine` tag also stop update? People, or at least I, choose this tag and that means I know what I will get. 

Let me say it: Not everyone work for a big woodpecker with an admin, more people just leave an instance, write some script and never open it then. The only result of dropping `latest` is that they will NEVER KNOW there is version 3 because woodpecker Is just a small app in their long list and the pull error will be ignored. Sure they will keep in version 2 and work for several years and even never complains. That's why I reply that 2 months later. Not everyone keeps an eye on github and docker hub. 

I still want a **stable** tag use latest stable version, not CD one. It's fine it don't name `latest`.

**Comment by IamIpanda** [comment]
> A rolling tag across major versions would have likely meant that your CI stopped working silently for that period you didn't watch it.
> 
> Not matter if large or small instance, removing it helped you just now to not break your pipelines.
> 
> While not every major release might be "as breaking" as the previous ones were, I still think this is the best way forward.
> 
> Once established, users know it and the scenario above won't occur. You are free to check for new upgrades whenever it fits. Until then, this policy protects you.
> 
> An additional side effect is that people won't start with latest, protecting them from being unable to downgrade to the latest release due to DB schema migration.

Not everyone work with a big woodpecker which can't break.
Not everyone keep an eye for github for upgrade. What I only do is executing docker pull.
Not everyone use watchtower.
let me repeat, for me, BRAEKING IS EXPECTED, `I don't know there is update` is not expected.
Let me take that as an example: I use Arch.

Sure people shouldn't take `latest` tag in this scene, but I don't want `next` tag because that's a CD version. I want just a simple latest stable version tag, even though its upgrade will break my pipelines, because **I'm not a heavy user, woodpecker break down for several days won't kill me**. Do you really want to stick on an old version woodpecker which still integrate `DRONE_CI` variables?

**Pull request merged**
