### PR TITLE
Add Jsonnet support

### PR DESCRIPTION
**Pull request by qwerty287**
Jsonnet is a templating language for JSON.

Example for a pipeline config (running with local backend):
```jsonnet
{
    pipeline: [
        {
            name: "bash-step",
            image: "bash",
            commands: ["echo Hello " + self.image + "!"],
        },
        self.pipeline[0] { name: "zsh-step", image: "zsh" },
    ]
}
```

which is evaluated into:
```json
{
   "pipeline": [
      {
         "commands": [
            "echo Hello bash!"
         ],
         "image": "bash",
         "name": "bash-step"
      },
      {
         "commands": [
            "echo Hello zsh!"
         ],
         "image": "zsh",
         "name": "zsh-step"
      }
   ]
}
```

### CODE REVIEW

**Comment by 6543** [comment]
I'm against it and for a global "compile" step that is plugin based ..

@anbraten ?

**Review by 6543 — CHANGES_REQUESTED** [review]
as per comment - we need to chat about this clearly

**Comment by lafriks** [comment]
I also agree that this should be made plugable at least by clear interface than they could be either builtin or external plugins

**Comment by 6543** [comment]
still thanks for looking into it :)

**Comment by 6543** [comment]
->  #1400

**Pull request closed without merging**
