### PR TITLE
Change default icon size to 20

### PR DESCRIPTION
**Pull request by xoxys**
In most places, we use icons right beside text. This PR changes the default icon size to `20` as this fits better with the default text size. 

Before:

image

After:

image

### CODE REVIEW

**Review by pat-s — APPROVED** [review]
Agree that it fits better.

**Comment by pat-s** [comment]
image

This is mad. So when the reviewer merges main as the last person, the review isn't counted 👀

**Comment by xoxys** [comment]
Yeah @qwerty287 was reporting this in our internal chat already. Maybe @woodpecker-ci/owner can check if we can disable it.

**Comment by xoxys** [comment]
Lol... it was enough to add another commit to ensure the last commit was not done by the approver? GitHub you are drunk.

**Pull request merged**
