### PR TITLE
Unify pipeline status icons

### PR DESCRIPTION
**Pull request by xoxys**
I know this might be controversial and there were already a lot of back and forth by the pipeline status icons. But right now it is kind of inconsistent, e.g. status `success`, `running` and `skipped` are circled icons while others are not. I would really like to harmonize it and use `circleOutline` icons for all pipeline status icons.

image

### CODE REVIEW

**Comment by anbraten** [comment]
Why are we migrating to the circle icons anyways we had: #2783 🤔

**Comment by pat-s** [comment]
👋️ hey guys, just trying to help. How about doing polls among maintainers on such subjective UI things? This would eliminate the 1:1 frictions and allows us to have more of a democratic way of moving forward.

**Comment by xoxys** [comment]
Polls are fine for me, but often hard to get a majority as some maintainers are not participating or only read messages infrequently.

**Comment by anbraten** [comment]
The reason we changed it before was that there are circle versions missing for some icons and therefore we sometimes mixed circle and none circle icons which we wanted to avoid. Seems like #3809 changed them unrelated to the plugin migration. Can't see a reason for any new discussions 🙃

**Comment by xoxys** [comment]
For the status, not a single icon I can see is missing a circleOutline version.

> Can't see a reason for any new discussions 🙃

There was never a discussion. You have not explained your reasons on the linked PR and feedback on this PR was ignored :shrug:  However, feel free to close this PR...

**Comment by anbraten** [comment]
> There was never a discussion. 

We had it in another PR or chat (not interested in searching the comment / message atm 😅). 

The service gear would stay without a circle?

Screenshot from 2024-11-19 11-26-13

> However, feel free to close this PR... I feel a bit disappointed now as I have a feeling that efforts put into UI got blocked quite often...

Please know that review comments are meant to improve the final outcome and ensure we’ve considered all perspectives.

**Comment by pat-s** [comment]
> Polls are fine for me, but often hard to get a majority as some maintainers are not participating or only read messages infrequently.

I see the issue but this is similar to the other governance-related issue we had: if we just continue to merge such PRs which are actively debated or contain subjective parts like UI changes with one maintainer approval, we might make the majority unhappy or force even a revert with the argument "I didn't see it and couldn't even veto it". In addition, this causes friction among maintainers and eventually leads to "everyone quickly merges subjective changes to not even allow much of a discussion".

The same applies to opinions of owners IMO, i.e. they shouldn't be a hard veto for such changes if "enough" people liked it/agreed on it.

*All the above is  without any opinion on the changes of this PR!*

So we need to find a way to 

- allow all maintainers to cast a vote in a reasonable time
- decide what the (majority) count should be that is required for merge (doesn't necessarily need to be > 50% of possible votes IMO)

(Yes I know this is off-topic and should be moved to a discussion but there it will likely go stale (?)).

Currently, the [maintainers team](https://github.com/orgs/woodpecker-ci/teams/maintainers) consists of 8 real people of which 6 are reasonably active in such discussions.

As we can't enforce votes in timespan X from all members, I think we need to work with relative votes. In addition, the tagging of the maintainers team is used inflationary and most don't even look at the issues therefore.
Hence I propose the following:

- No maintainer group tags anymore by default in PRs
- Every UI-related change is coupled by a comment requesting to vote on the changes and tags the maintainers team (thumbs up/down)
- The vote is kept open for three days and if there's a majority in favor of the changes, they get merged, otherwise not.
- Only maintainer votes are counted, other user votes are discarded

---

Sorry for the wall of text. Yet, I think it is needed to find to reduce anger/emotions in decision making (I'll include myself here as well) and improves governance overall. @xoxys @anbraten what do you think?

**Comment by xoxys** [comment]
> We had it in another PR or chat (not interested in searching the comment / message atm 😅).

Just add context to the PR description could solve it (we should improve in this area anyway)

> The service gear would stay without a circle?

The gear is already a circle shape, which fits optically for me. Technically, I get your point, and we could search for another circleOutline icon (IMO a gear is not really symbolic of services)

> Please know that review comments are meant to improve the final outcome and ensure we’ve considered all perspectives.

You're right, sorry for my reaction, I'm trying to improve here.

**Comment by 6543** [comment]
My criteria are just: contrast between them is high enouth; symboles can be spotted as different one evenif monocrome; the bird for running pipelines stays :)

So a vote is fine by me, i will just intentionaly abstain to let people witj better UI/UX experience deside it :)

**Comment by xoxys** [comment]
@woodpecker-ci/maintainers please vote on this post :+1: use circled pipeline icons :-1: use not circled icons from https://github.com/woodpecker-ci/woodpecker/pull/2783

**Pull request merged**
