### PR TITLE
Enable golangci linter goconst

### PR DESCRIPTION
**Pull request by xoxys**
Split out from https://github.com/woodpecker-ci/woodpecker/pull/2960

### CODE REVIEW

**Review by 6543 — APPROVED** [review]

**Comment by lafriks** [comment]
Not sure I like this linter 🤣

**Comment by xoxys** [comment]
No strong opinion, feel free to close unmerged.

**Comment by lafriks** [comment]
It's too strict on values as can be seen already in a lot of places need to add nolint comment, personally I don't like it because of it

**Comment by xoxys** [comment]
Wel... There are only a few places where excludes were added... However.

**Comment by xoxys** [comment]
Please make a decision first if the linter should be activated or not before I spend more time on it.

**Pull request closed without merging**
