### PR TITLE
Match account icon hover background shape with account icon shape

### PR DESCRIPTION
**Pull request by dvjn**

### CODE REVIEW

**Review by anbraten — APPROVED** [review]

**Review by anbraten — CHANGES_REQUESTED** [review]
Cloud you add screenshots?

Why don't you want it to be round anymore?

**Comment by dvjn** [comment]
@anbraten

| hover effect now | hover effect earlier |
| --- | --- |
| image | image |


> Isn't the problem that the underlying image is not rounded?

yes, but i think that was an intentional decision.

**Review by 6543 — APPROVED** [review]

**Comment by 6543** [comment]
we did a poll and got "square with rounded corners", I would say this change is in the right direction, we just somehow need to adapt the "pipeline runing" indicator to match the theme too ...

**Comment by dvjn** [comment]
> we just somehow need to adapt the "pipeline runing" indicator to match the theme too ...

@6543 +1

Also, then we need to convert all the icon buttons background to "square with rounded corners" for consistency sake

**Comment by 6543** [comment]
how many do we have of them?

**Comment by dvjn** [comment]
> how many do we have of them?

a lot, but I think they originate from the same component so would be strightforward

**Comment by anbraten** [comment]
I am not convinced yet. Rounded square would look quite special as almost all our icons are based on a circle: 
image

Should we really make them squares on hover?

**Comment by dvjn** [comment]
or we can go the github approach of highlighting an icon button only using the foreground color

**Comment by anbraten** [comment]
was implemented by #2000

**Pull request closed without merging**
