### PR TITLE
Force agent labels to be set on pipelines as well

### PR DESCRIPTION
**Pull request by xoxys**
Fixes: https://github.com/woodpecker-ci/woodpecker/issues/2634

### CODE REVIEW

**Comment by xoxys** [comment]
Yes it would. We can still decide to introduce another config option but is said in the issue the current behavior doesnt make sense to me.

**Comment by xoxys** [comment]
What's the best way to make it none-breaking?

What I tried is to add a flag `WOODPECKER_FILTER_LABELS_REQUIRED=true/false` but how to pass it to the `grpc.Next` method? I think the parameter can be added to the `rpc.Filter` struct, but either way this would require changes to protobuf or am I wrong?

**Comment by xoxys** [comment]
Sure we could, I still think this should be better configurable but open for other decisions.

**Comment by 6543** [comment]
this is not easy as the labels are currently used to let agents "advertice capabilitys/propertys" the pipelines can target.

so make them mandatory by default will break all existing pipelines and add unnecessary complexytiy to the config.

to make an label required should be optional!

I think we could either add some prefix like `!`  to indicate such .... etc

**Comment by 6543** [comment]
image

ontop of https://github.com/woodpecker-ci/woodpecker/pull/4141:
```diff
 ### `WOODPECKER_AGENT_LABELS`
 
 > Default: empty
 
 Configures custom labels for the agent, to let workflows filter by it.
 Use a list of key-value pairs like `key=value,second-key=*`. `*` can be used as a wildcard.
+If you use `!` as key prefix it is mandatory for the workflow to have that label set (without !) set and matched.
 By default, agents provide three additional labels `platform=os/arch`, `hostname=my-agent` and `repo=*` which can be overwritten if needed.
 To learn how labels work, check out the [pipeline syntax page](../20-usage/20-workflow-syntax.md#labels).
```

**Pull request closed without merging**
