### PR TITLE
Move link checks into cron-curated issue dashboard

### PR DESCRIPTION
**Pull request by pat-s**
Link checks often indicate failed CI checks. While the `static` run is not required, it takes time to inspect the failure and move on.
This is irritating and not helpful, as failing link checks often do not have any relation to the PR at hand.

This change moves the link checks out of the PR checks into a static issue dashboard which is updated daily by a CRON job.

This way:

- `static.yaml` could be added as a required CI check
- False-positive CI check noise gets reduced
- A static issue dashboard shows the up-to-date state of all links

### CODE REVIEW

**Comment by pat-s** [comment]
It shouldn't get closed. Link checks will never stop. Same with dependency checks.

**Comment by pat-s** [comment]
Hm, while I understand the motivation, I don't think this will ever apply. Actually I also like closing issues and keep things tidy, but there is no other way to pin such dashboard-like information in today's git hosters than within "issues".

I still think moving out the link checker from the always-running CI checks is an improvement.

**Comment by jolheiser** [comment]
What about using a "discussion" item instead?

**Comment by xoxys** [comment]
IMO it doesnt harm if there are a hand full pinned tracking issues. I like the idea.

**Comment by pat-s** [comment]
@woodpecker-ci/maintainers Any reviews?

**Comment by pat-s** [comment]
Sure, the question is only what the purpose of this issue would be? 
Simply for visual grouping? Feel free to create one 👍

**Comment by xoxys** [comment]
A dashboard label would make sense and helps with filtering 👍

**Pull request merged**
