### PR TITLE
Fix privileged steps in kubernetes

### LINKED ISSUE #3537: Woodpecker 2.4 breaks privileged steps/plugins with Kubernetes backend
This worked with WP 2.3 and Kubernetes backend:

```
  publish:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: *repo
      tags: 8h
```

Using WP 2.4 the docker daemon does not start.

Debugging the Pod manifest I see an empty security context and the docker daemon does not start.

This works with WP 2.4.1 but is not so user friendly:

```
  publish:
    image: woodpeckerci/plugin-docker-buildx
    privileged: true
    backend_options:
      kubernetes:
        securityContext:
          privileged: true
    settings:
      repo: *repo
      tags: 8h
      daemon.debug: "true"
```

See also: https://github.com/woodpecker-ci/woodpecker/issues/3482#issuecomment-2015672185_

### PR DESCRIPTION
**Pull request by anbraten**
closes #3537

### CODE REVIEW

**Comment by xoxys** [comment]
Yep, it looks like it ignores the entire discussion from the linked PR.

**Comment by anbraten** [comment]
Step privileged is only set in case its a plugin and in the list of privilege plugins:

https://github.com/woodpecker-ci/woodpecker/blob/75803dba41a0a276af34606f6330fedf944873b9/pipeline/frontend/yaml/compiler/convert.go#L130

Or if the `privileged: true` option is set. 

In case a user tries to set that option without having a trusted repo he will get a linter error from:

https://github.com/woodpecker-ci/woodpecker/blob/b2cfa37682b002360a63b65213e473d290a32e7d/pipeline/frontend/yaml/linter/linter.go#L115

https://github.com/woodpecker-ci/woodpecker/blob/b2cfa37682b002360a63b65213e473d290a32e7d/pipeline/frontend/yaml/linter/linter.go#L153

**Comment by anbraten** [comment]
Setting the security-context / user / group to `0` (root) or fs-group etc is checked here and will only work for privileged steps which can only be allowed by trusted plugins or by setting `privileged: true` which can only be done if the repo is trusted: 

https://github.com/woodpecker-ci/woodpecker/blob/9cc5d0875c9172c0c7ffd09e150d42bed94c9e3d/pipeline/backend/kubernetes/pod.go#L391

https://github.com/woodpecker-ci/woodpecker/blob/9cc5d0875c9172c0c7ffd09e150d42bed94c9e3d/pipeline/backend/kubernetes/pod.go#L445

**Comment by anbraten** [comment]
> Yep, it looks like it ignores the entire discussion from the linked PR.

It solves the issue that the `woodpeckerci/plugin-docker-buildx` plugin can only be used if a `securityContext` is explicitly configured. For already privileged steps (trusted plugins) this wont be necessary anymore now.

**Comment by anbraten** [comment]
My goal was to simply fix the actual issue #3537 first. Changing the logic to require a trusted repo for the `buildx` plugin is somehow a different change IMO (at least that's how the docker backend works and the docs explain it to the users) . 

Requiring a trusted repo to manually set the `securityContext` could be done separately.

**Comment by xoxys** [comment]
I would suggest to involve the people that have created, contributed and tested the original PR. This entire discussion should have been done in the existing PR instead of just starting the a new one...

**Comment by anbraten** [comment]
Thanks for approving.

> Please use a new discussion to revert these changes and make it how it should work ideally, but the bug should be fixed asap.

We can just move on with #3538 as this is part of it.

**Pull request merged**
