### PR TITLE
Fix typos in docs

### PR DESCRIPTION
**Pull request by yardenshoham**
I ran [cspell](https://www.npmjs.com/package/cspell) and fixed the typos it detected

also add cspell to gitpod

### CODE REVIEW

**Comment by 6543** [comment]
does there exist an official docker image for cspell?

**Comment by 6543** [comment]
yes `docker run -v $PWD:/workdir ghcr.io/streetsidesoftware/cspell:latest "**"` -> https://github.com/streetsidesoftware/cspell/issues/3270

so we could add it to our ci pipeline

**Comment by yardenshoham** [comment]
Well, it would add a lot of overhead. You'd have to add each word it doesn't recognize (e.g. `myfile`) into a file

**Comment by yardenshoham** [comment]
We could add it as a vscode extension to gitpod

**Comment by 6543** [comment]
Yes please do so in this pull

**Review by 6543 — APPROVED** [review]

**Pull request merged**
