### PR TITLE
Switch to go vanity urls

### PR DESCRIPTION
**Pull request by 6543**
close https://github.com/woodpecker-ci/infrastructure/issues/4

switch from `github.com/woodpecker-ci/woodpecker/...` to `go.woodpecker-ci.org/woodpecker/...`

### CODE REVIEW

**Review by anbraten — CHANGES_REQUESTED** [review]
Would block this until we get the needed PRs for the release merged.

**Comment by 6543** [comment]
I'd like to get that int v2.0.0 as backports will be easyer this way :)

**Comment by pat-s** [comment]
Couldn't this also go into 2.1.0? If @6543 resolves all issues quickly, 2.0.0 is also fine, but I don't think we should necessarily wait for this?

**Comment by 6543** [comment]
I'll resolve conflicts :)

**Review by anbraten — COMMENTED** [review]
Had a look at all changes and those seem fine. However some files are missing.

**Review by anbraten — APPROVED** [review]

**Comment by anbraten** [comment]
Pleas upgrade depending packages like autoscaler accordingly.

**Pull request merged**
