### PR TITLE
Unregister stateless agents from server on termination

### LINKED ISSUE #2027: Kubernetes backend : too many agents registered
### Component

server, agent

### Describe the bug

I noticed that I have a lot of agents declared in http://my-ci/admin/settings#agents.

After few tests, I noticed that every time I restart a pod with an agent, it registers itself, adding a new agent declared in http://my-ci/admin/settings#agents.

Note : in the Kubernetes world, pods can be deleted at any time, for load balancing, draining a node, upgrading, or any other good or bad reason. With the Helm chart provided at [woodpecker-ci/helm](https://github.com/woodpecker-ci/helm) the pods are under control of a Deployment, which means that they are stateless. Any new pod has no idea of the registration of the older one.

Bug : some cleanup should be done automatically when a pod is removed.

Suggestion : when an pod terminates, the agent should unregister before leaving.

### System Info

```shell
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"next-2e851ba4"}

Backend: Kubernetes
```

### Additional context

_No response_

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

### PR DESCRIPTION
**Pull request by zc-devs**
Closes #2027

### CODE REVIEW

**Comment by zc-devs** [comment]
Agent log:
```
{"level":"info","time":"2023-10-18T11:20:13Z","caller":"/src/cmd/agent/config.go:41","message":"no agent config found at '/etc/woodpecker/agent.conf', start with defaults"}
{"level":"error","error":"open /etc/woodpecker/agent.conf: no such file or directory","time":"2023-10-18T11:20:13Z","caller":"/src/cmd/agent/config.go:70","message":"could not persist agent config at '/etc/woodpecker/agent.conf'"}
{"level":"debug","time":"2023-10-18T11:20:13Z","caller":"/src/cmd/agent/agent.go:194","message":"Agent registered with ID 68"}
{"level":"info","time":"2023-10-18T11:20:13Z","caller":"/src/cmd/agent/agent.go:243","message":"Starting Woodpecker agent with version 'next-faab46cf9b' and backend 'kubernetes' using platform 'linux/amd64' running up to 1 pipelines in parallel"}

{"level":"info","time":"2023-10-18T11:21:00Z","caller":"/src/cmd/agent/agent.go:127","message":"Termination signal is received, shutting down"}
{"level":"debug","time":"2023-10-18T11:21:00Z","caller":"/src/cmd/agent/agent.go:132","message":"Unregistering agent from server"}
```

Server log:
```
{"level":"debug","time":"2023-10-18T11:21:00Z","caller":"server/grpc/rpc.go:361","message":"unregistering agent with ID 68"}
{"level":"info","component":"xorm","time":"2023-10-18T11:21:00Z","caller":"server/store/datastore/xorm.go:77","message":"[SQL] DELETE FROM \"agents\" WHERE \"id\"=$1 [68] - 1.76971ms"}
```

**Comment by pat-s** [comment]
Uhh nice! I am also having this issue and was hoping that somebody might be able to fix it 👍

**Comment by zc-devs** [comment]
It is not. I can add one `if` and make it kube-specific, but it would be kind of discrimination :)

**Comment by pat-s** [comment]
Fair enough, I only saw the amount of logs and messages in the k8s instances but the issue might be a general one.

**Review by 6543 — APPROVED** [review]
like it

**Comment by 6543** [comment]
made it so you can trigger this behaviour intententional by add `--agent-config ""` arg or set `WOODPECKER_AGENT_CONFIG_FILE=""`

**Review by lafriks — APPROVED** [review]

**Pull request merged**
