### PR TITLE
Only show commit title

### PR DESCRIPTION
**Pull request by qwerty287**
https://github.com/woodpecker-ci/woodpecker/issues/2359

### CODE REVIEW

**Comment by xoxys** [comment]
You might want to add it to the pipeline list as well
image

**Comment by anbraten** [comment]
And in

- web/src/components/pipeline-feed/PipelineFeedItem.vue

image

**Comment by xoxys** [comment]
Dont know if the hover worsk everywhere. E.g. in the pipeline list there is no explicit hover for the commit message only one hover for the entire pipeline.

**Comment by xoxys** [comment]
:+1: I though it might now work because there is already a hover for the entire row. Anyway, my fault, works.

**Pull request merged**
