### PR TITLE
Add option disable cron

### PR DESCRIPTION
**Pull request by 6543**

### CODE REVIEW

**Comment by 6543** [comment]
... i'd like to have it as option too :)

**Comment by aozomaro** [comment]
fyi, disabling the cron jobs proved to not be necessary to solve #2827. what really solved the problem was two things:
1) Using non sql lite db 
2) Adding a reverse proxy in front of woodpecker-server (this was the big one that really got me up and running)

**Comment by pat-s** [comment]
@6543 What would be the motivation to disable cron? Just asking, as the code becomes more complex by these additions and I don't really see what the advantage is as cron is one of the core features of a CI. Security?

**Comment by aozomaro** [comment]
> @6543 What would be the motivation to disable cron? Just asking, as the code becomes more complex by these additions and I don't really see what the advantage is as cron is one of the core features of a CI. Security?

Original problem was database being locked and receiving locking errors frequently which caused nothing to work (agents unable to report that they’ve closed the stream and as a result the server would panic when it sent a message after the stream had already closed)

I ended up solving the problem by:

* switching to Postgres (partially worked, server took longer to crash but crashed when the job queue had 4 pull requests running by checks)
* Adding a reverse proxy (this made the problem vanish)
* 
that being said we probably don’t need this anymore and just need to update docs/add disclaimers around how to run this in production mode

**Review by anbraten — CHANGES_REQUESTED** [review]
Per comment

**Comment by pat-s** [comment]
@aozomaro Thanks for the summary.

I'm a bit confused now: @anbraten Does your comment imply to close this PR? @6543 seems to view this PR as a feature despite not being needed anymore for the linked issue.

(No opinion from my side, just wanted to moderate this one initially to move forward)

**Comment by anbraten** [comment]
Yes, I would close this PR as I don't see a serious reason to disable cron.

**Pull request closed without merging**
