### PR TITLE
Fix badge url with rootpath

### LINKED ISSUE #3032: Wrong badgeUrl when rootPath is not empty in the page of repo badge settings
### Component

web-ui

### Describe the bug

When rootPath is not empty the badge image src link is wrong in the page of repo badge settings.

### System Info

```shell
{
    "source": "https://github.com/woodpecker-ci/woodpecker",
    "version": "2.1.0"
}
```

### Additional context

image

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

### PR DESCRIPTION
**Pull request by andyhan**
Fix #3032 again.

### CODE REVIEW

**Comment by 6543** [comment]
Did i miss something?!?

**Comment by andyhan** [comment]
> I just tried to understand this change, but I don't get it. It should work with relative paths too, shouldn't it?

My last commit to fix the badgeUrl issue, strip the rootPath from the baseUrl, and add rootPath to the badgeUrl variable as a prefix. But for HTML or Markdown Syntax of Badge output，it needs a woodpecker repository link as well, that link is missing roopPath.
image

**Comment by andyhan** [comment]
> I don't see how this is the case.
> 
> See
> 
> https://github.com/woodpecker-ci/woodpecker/blob/db45b9032ca73d79d3c4a3f25cb5056b0018b386/web/src/components/repo/settings/BadgeTab.vue#L106
> 
> -> markdown/html URL = baseUrl + badgeUrl
> And in
> 
> https://github.com/woodpecker-ci/woodpecker/blob/db45b9032ca73d79d3c4a3f25cb5056b0018b386/web/src/components/repo/settings/BadgeTab.vue#L90
> 
> 
> badgeUrl contains the rootPath.

Yes, badgeUrl contains the rootPath, but repoUrl doesn't. markdown/html Badge content also includes the repoUrl, that is the problem.

https://github.com/woodpecker-ci/woodpecker/blob/db45b9032ca73d79d3c4a3f25cb5056b0018b386/web/src/components/repo/settings/BadgeTab.vue#L92
ci/woodpecker/blob/db45b9032ca73d79d3c4a3f25cb5056b0018b386/web/src/components/repo/settings/BadgeTab.vue#L106
https://github.com/woodpecker-ci/woodpecker/blob/db45b9032ca73d79d3c4a3f25cb5056b0018b386/web/src/components/repo/settings/BadgeTab.vue#L110

**Comment by andyhan** [comment]
> I see your point, but then this PR doesn't fix the issue, but will break everything instead. Can't you just add the rootPath to repoUrl?

OK, I can do as you say.

**Pull request closed without merging**
