### PR TITLE
Add EditorConfig-Checker Plugin to docs

### PR DESCRIPTION
**Pull request by 6543**
REPO: https://codeberg.org/woodpecker-plugins/editorconfig-checker

DOCS: https://woodpecker-ci-woodpecker-pr-4371.surge.sh/plugins/EditorConfig%20Checker

### CODE REVIEW

**Comment by xoxys** [comment]
Why? Im still not a fan of this wrapping approach as it adds a lot of overhead

**Comment by xoxys** [comment]
Ah this time its a real plugin, nevermind

**Comment by pat-s** [comment]
While I also don't like the idea of shell wrappers as plugins without any additional beef behind it, I think the overall idea is to have a large suite of "plug and play" plugins that are perceived as "secure" compared to normal steps that would execute the same job.

**Comment by 6543** [comment]
Plungins are not only for security ... they are also for beginners to not write scripts.

In this case the main benefit is feedback on sucess and the option to only lint changed files (via simple bool option)

As told the target audience of such plugins (prettier, pm, editorconfig, ...) are beginners not advanced users.

And if it exist we cam dogfood ...

I think I need to make an actual survay about this to support my argument with hard numbers 🤔.

**Review by xoxys — APPROVED** [review]

**Pull request merged**
