### PR TITLE
Fix skipped pipelines model (v2)

### PR DESCRIPTION
**Pull request by xoxys**
Alternative approach to https://github.com/woodpecker-ci/woodpecker/pull/2923

This approach is using the existing mechanism to update pipeline definitions used for [gated repos](https://github.com/woodpecker-ci/woodpecker/blob/fb7619a5c842fe7e4b93fb8f86c849c9049084a3/server/pipeline/approve.go#L53-L60).

To avoid executing it twice in case of gated repos, I've moved the logic after the `model.StatusBlocked` check. Calling `setPipelineStepsOnPipeline` was removed, as this is done by `createPipelineItems` already.

Of course this approach is also not perfect as multiple calls to `parsePipeline` also have a price, but IMO avoids some race conditions and extra handling required for adding + deleting pipelines from the DB.

### CODE REVIEW

**Review by lafriks — APPROVED** [review]

**Comment by lafriks** [comment]
I think this is better approach than creating and deleting records in db

**Comment by xoxys** [comment]
Thanks for your feedback. As I'm not sure about possible side effects I would like for a second review.

**Comment by xoxys** [comment]
> Yes, this will probably cause some side effects.
> 
> 1. Pipelines are parsed twice. (Not sure if there's a way to go around this)

True but the exact code is executed twice on every single ci run for gated repos.


> 2. Empty pipeline env vars can cause yaml parsing issues like https://github.com/woodpecker-ci/woodpecker/issues/2002

Same here, if that is an issue the same issue exist for all gated repo jobs or am I missing something?

**Comment by xoxys** [comment]
Ok so we should better take the other approach and delete empty pipelines from DB again?

**Comment by xoxys** [comment]
Fully agree 🤣 If you would like to look into the entire issue on your own thats ok for me as well. We dont need to use one of my approaches.

**Comment by xoxys** [comment]
Sure, fine for me as well.

**Pull request closed without merging**
