### PR TITLE
Fix multiline secrets replacer

### LINKED ISSUE #694: `*` spamming and GPRC error after latest pull of 0.15.0-rc1
### Component

server, agent, web-ui

### Describe the bug

I pulled the latest `woodpeckerci/woodpecker-server` and `woodpeckerci/woordpecker-agent` some hours ago, and there are two unwanted behaviors now:

1. Log spammed with `*`
see https://ci.friendi.ca/friendica/friendica/build/124/8
The `step` output is now filled with `*` before and after each letter in the output, like
```console
********+******** ********g********i********t******** ********i********n********i********t******** ********
********h********i********n********t********:******** ********U********s********i********n********g******** ********'********m********a********s********t********e********r********'******** ********a********s******** ********t********h********e******** ********n********a********m********e******** ********f********o********r******** ********t********h********e******** ********i********n********i********t********i********a********l******** ********b********r********a********n********c********h********.******** ********T********h********i********s******** ********d********e********f********a********u********l********t******** ********b********r********a********n********c********h******** ********n********a********m********e******** ********
********h********i********n********t********:******** ********i********s******** ********s********u********b********j********e********c********t******** ********t********o******** ********c********h********a********n********g********e********.******** ********T********o******** ********c********o********n********f********i********g********u********r********e******** ********t********h********e******** ********i********n********i********t********i********a********l******** ********b********r********a********n********c********h******** ********n********a********m********e******** ********t********o******** ********u********s********e******** ********i********n******** ********a********l********l******** ********
********h********i********n********t********:******** ********o********f******** ********y********o********u********r******** ********n********e********w******** ********r********e********p********o********s********i********t********o********r********i********e********s********,******** ********w********h********i********c********h******** ********w********i********l********l******** ********s********u********p********p********r********e********s********s******** ********t********h********i********s******** ********w********a********r********n********i********n********g********,******** ********c********a********l********l********:******** ********
********h********i********n********t********:******** ******** ********
```

2. GPRC errors
The log is filled with the same error `src/pipeline/rpc/client_grpc.go:287 > grpc error: log(): code: Internal: rpc error: code = Internal desc = grpc: error while marshaling: string field contains invalid UTF-8 error="rpc error: code = Internal desc = grpc: error while marshaling: string field contains invalid UTF-8"` all over, like
```console
woodpecker-runner-1    | 10:23PM ERR src/pipeline/rpc/client_grpc.go:287 > grpc error: log(): code: Internal: rpc error: code = Internal desc = grpc: error while marshaling: string field contains invalid UTF-8 error="rpc error: code = Internal desc = grpc: error while marshaling: string field contains invalid UTF-8"
woodpecker-runner-1    | 10:23PM ERR src/pipeline/rpc/client_grpc.go:287 > grpc error: log(): code: Internal: rpc error: code = Internal desc = grpc: error while marshaling: string field contains invalid UTF-8 error="rpc error: code = Internal desc = grpc: error while marshaling: string field contains invalid UTF-8"
woodpecker-runner-1    | 10:23PM ERR src/pipeline/rpc/client_grpc.go:287 > grpc error: log(): code: Internal: rpc error: code = Internal desc = grpc: error while marshaling: string field contains invalid UTF-8 error="rpc error: code = Internal desc = grpc: error while marshaling: string field contains invalid UTF-8"
woodpecker-runner-1    | 10:23PM ERR src/pipeline/rpc/client_grpc.go:287 > grpc error: log(): code: Internal: rpc error: code = Internal desc = grpc: error while marshaling: string field contains invalid UTF-8 error="rpc error: code = Internal desc = grpc: error while marshaling: string field contains invalid UTF-8"
woodpecker-runner-1    | 10:23PM ERR src/pipeline/rpc/client_grpc.go:287 > grpc error: log(): code: Internal: rpc error: code = Internal desc = grpc: error while marshaling: string field contains invalid UTF-8 error="rpc error: code = Internal desc = grpc: error while marshaling: string field contains invalid UTF-8"
woodpecker-runner-1    | 10:23PM ERR src/pipeline/rpc/client_grpc.go:287 > grpc error: log(): code: Internal: rpc error: code = Internal desc = grpc: error while marshaling: string field contains invalid UTF-8 error="rpc error: code = Internal desc = grpc: error while marshaling: string field contains invalid UTF-8"
woodpecker-runner-1    | 10:23PM ERR src/pipeline/rpc/client_grpc.go:287 > grpc error: log(): code: Internal: rpc error: code = Internal desc = grpc: error while marshaling: string field contains invalid UTF-8 error="rpc error: code = Internal desc = grpc: error while marshaling: string field contains invalid UTF-8"
```

### System Info

```shell
version	"0.15.0-rc1"
```
```docker-compose
version: '3'

services:
  server:
    image: woodpeckerci/woodpecker-server:latest
    volumes:
      - woodpecker-vol-1:/var/lib/woodpecker/
    restart: always
    ports:
      - "0.0.0.0:9000:9000"
      - "0.0.0.0:8000:8000"
    extra_hosts:
      - "git.friendi.ca:192.168.173.33"
    environment:
      - WOODPECKER_OPEN=true
      - WOODPECKER_HOST=https://ci.friendi.ca
      - WOODPECKER_GITHUB=true
      - WOODPECKER_GITHUB_CLIENT=XXXX
      - WOODPECKER_GITHUB_SECRET=XXXX
      - WOODPECKER_AGENT_SECRET=XXXX
      - WOODPECKER_ADMIN=XXXX,XXXX,XXXX,XXXX
      - WOODPECKER_REPO_OWNERS=XXXX,XXXX,XXXX,XXXX
      - WOODPECKER_DEBUG_PRETTY=true
      - WOODPECKER_DEBUG_NOCOLOR=false

  runner:
    image: woodpeckerci/woodpecker-agent:latest
    restart: always
    privileged: true
    userns_mode: host
    depends_on:
      - server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    extra_hosts:
      - "git.friendi.ca:192.168.173.33"
    environment:
      - WOODPECKER_SERVER=server:9000
      - WOODPECKER_AGENT_SECRET=XXXX
      - WOODPECKER_MAX_PROCS=4
      - WOODPECKER_HOSTNAME=runner.ci.friendi.ca
      - WOODPECKER_DEBUG_PRETTY=true
      - WOODPECKER_DEBUG_NOCOLOR=false

  releaser:
    image: woodpeckerci/woodpecker-agent:latest
    restart: always
    privileged: true
    userns_mode: host
    depends_on:
      - server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    extra_hosts:
      - "git.friendi.ca:192.168.173.33"
    environment:
      - WOODPECKER_SERVER=server:9000
      - WOODPECKER_AGENT_SECRET=XXXX
      - WOODPECKER_MAX_PROCS=2
      - WOODPECKER_HOSTNAME=releaser.ci.friendi.ca
      - WOODPECKER_PLATFORM=releaser/release 
      - WOODPECKER_DEBUG_PRETTY=true
      - WOODPECKER_DEBUG_NOCOLOR=false
      - WOODPECKER_ENVIRONMENT=node:releaser

volumes:
  woodpecker-vol-1:
    name: woodpecker_data
```

### Additional context

_No response_

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy).

### PR DESCRIPTION
**Pull request by nupplaphil**
Fixes #694 
FollowUp #671

### CODE REVIEW

**Review by anbraten — APPROVED** [review]

**Comment by anbraten** [comment]
Thank you for your investigation on that issue. ❤️

**Comment by nupplaphil** [comment]
tbh I'm not sure how I can interpret the failed test and what I can do now

**Comment by 6543** [comment]
let me check

**Review by 6543 — APPROVED** [review]

**Comment by 6543** [comment]
heh I did trim but not had an idea there could be newlines in-between :D

**Comment by nupplaphil** [comment]
> heh I did trim but not had an idea there could be newlines in-between :D

secrets are filled with user **text** input, so we can expect every kind of input madness as usual :D

**Comment by 6543** [comment]
I thought about one char secrets - but that's the user vault so i didnt add a min text lengh check ;) - but your case is a valid one!

**Pull request merged**
