### PR TITLE
Remove unrelated public events from user feed

### LINKED ISSUE #971: Synchronize status between active view, the right pane, and the top (navigation) bar
### Component

web-ui

### Describe the bug

When a pipeline is triggered, if I browse over the view/screen where the steps are displayed, when the pipeline finishes, the interface "gives the impression" the pipeline is still in progress based on some indicators, specifically, there will still be a section with the `user/repository` (with the blue two-dots animation) and the circle in the top (navigation) bar.

Notice that when it finishes, a section with the `user/repository` is created as well right before the top one with the correct "finished" status.

So it's just a matter of synchronizing some elements and hiding/removing them from the DOM — my guess :thinking:

### System Info

```shell
Codeberg's Woodpecker CI
```

### Additional context

_No response_

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

### PR DESCRIPTION
**Pull request by MFTabriz**
fixes: https://codeberg.org/Codeberg-CI/feedback/issues/28

closes #971

### CODE REVIEW

**Comment by MFTabriz** [comment]
Looks like the CI is failing the same way as [for the base repo](https://ci.woodpecker-ci.org/woodpecker-ci/woodpecker/pipeline/4595/20)

**Comment by anbraten** [comment]
Thanks for having a look on this. 

Notes for testing:
check if the user gets pipeline updates (not only the sidebar, but most importantly new pipelines and updates to the workflows and steps)
- for own private projects
- for org private projects
- for public projects the user does not directly own, but is allowed to see
- for public projects as unauthenticated users

**Comment by MFTabriz** [comment]
> Notes for testing: check if the user gets pipeline updates (not only the sidebar, but most importantly new pipelines and updates to the workflows and steps)
> 
>     * for own private projects
> 
>     * for org private projects
> 
>     * for public projects the user does not directly own, but is allowed to see
> 
>     * for public projects as unauthenticated users

Are there any automated tests for these or do we need to add them?

**Comment by anbraten** [comment]
I just wrote it down for manual testing 😅There are not automatic tests for this atm. Adding them would probably be a lot of work as those would be almost integration tests.

**Comment by anbraten** [comment]
I have manually tested it and my concerns have been confirmed. This change doesn't solve the problem. Instead a user without direct access does no longer get updates of projects he does not own.

**Comment by MFTabriz** [comment]
> I have manually tested it and my concerns have been confirmed. **This change doesn't solve the problem**. Instead a user without direct access does no longer get updates of projects he does not own.

Thanks for checking this out. Do you mean the issue with seeing the public repos in the sidebar is still there after this patch?

**Comment by anbraten** [comment]
> Thanks for checking this out. Do you mean the issue with seeing the public repos in the sidebar is still there after this patch?

That's  "fixed". But it also stops all other events of public repos. 

For example you can have a look at the https://ci.woodpecker-ci.org/woodpecker-ci/woodpecker repo without being authenticated at all as the repo is public. With your change the user isn't getting any updates for the pipelines anymore. So the list in the middle (not the sidebar) would not update from running to successful.

**Comment by anbraten** [comment]
I am currently having a look at the code. In stead of limiting the events in the backend for now I would add some kind of a view filter to the UI which hides projects you are not part of from the sidepanel and the "my" projects / repos list.

**Comment by MFTabriz** [comment]
> I am currently having a look at the code. In stead of limiting the events in the backend for I would add some kind of a view filter to the UI which hides projects you are not part of from the sidepanel and the "my" projects / repos list.

I would be more in favor of filtering them somehow in the backend (for example based on the page the user is on). Sending all public CI events to all the users would create lots of unnecessary traffic specially for the servers with a many public repos.

**Comment by anbraten** [comment]
> I would be more in favor of filtering them somehow in the backend (for example based on the page the user is on). Sending all public CI events to all the users would create lots of unnecessary traffic specially for the servers with many public repos.

The biggest problem with that approach is that the backend needs to know the repos a user is interested in as its not only the repos the user owns, but also public repos the user is having a look at.

**Comment by MFTabriz** [comment]
> The biggest problem with that approach is that the backend needs to know the repos a user is interested in as its not only the repos the user owns, but also public repos the user is having a look at. (Possible, but requires quite some logic).

Is it possible instead of subscribing to the default Pubsub topic (`topic/events`) [here]( https://github.com/woodpecker-ci/woodpecker/blob/a884e13885b9519c6c7bf7f6e41a2f177207b50d/server/api/stream.go#L82),  to subscribe to a topic based on the page url instead? For example something with user/repo of the current page's url appended to it.

**Comment by anbraten** [comment]
> Is it possible instead of subscribing to the default Pubsub topic (topic/events) [here](https://github.com/woodpecker-ci/woodpecker/blob/a884e13885b9519c6c7bf7f6e41a2f177207b50d/server/api/stream.go#L82), to subscribe to a topic based on the page url instead? For example something with user/repo of the current page's url appended to it.

That should be possible. It would require some refactors as the user needs to pass the topic name somehow.

For the beginning I have created #1453 which is a code cleanup of the Vue store and solves the problem quite easily.

**Comment by MFTabriz** [comment]
> > Is it possible instead of subscribing to the default Pubsub topic (topic/events) [here](https://github.com/woodpecker-ci/woodpecker/blob/a884e13885b9519c6c7bf7f6e41a2f177207b50d/server/api/stream.go#L82), to subscribe to a topic based on the page url instead? For example something with user/repo of the current page's url appended to it.
> 
> That should be possible. It would require some refactors as the user needs to pass the topic name somehow.
> 
> For the beginning I have created #1453 which is a code cleanup of the Vue store and solves the problem quite easily.

Thanks a lot! I opened #1454 to track that issue independently.

**Pull request closed without merging**
