### PR TITLE
Use full width header on pipeline view and show repo name

### PR DESCRIPTION
**Pull request by xoxys**
Ref: https://github.com/woodpecker-ci/woodpecker/discussions/2162#discussioncomment-6724450

**After:**
image

**Before:**

### CODE REVIEW

**Review by pat-s — APPROVED** [review]
LGTM

**Comment by xoxys** [comment]
Repo name not added yet. Will finish it during the weekend.

**Comment by xoxys** [comment]
I've also added some changes to the mobile view of the header. Still not perfect, but IMO more aligned now.

**Comment by xoxys** [comment]
@woodpecker-ci/maintainers if commits were added after the approval do we wait for a re-review or merge?

**Comment by 6543** [comment]
If they are minor the merge just verify it again (if they come from the one who merges well you should know when they are not minor anymore) and merge.

else yes rerequest it

**Comment by 6543** [comment]
PS: if you are not sure, just request you answered it yourselve

**Review by pat-s — APPROVED** [review]
Thanks for the effort!

**Pull request merged**
