### PR TITLE
Fix vscode settings

### PR DESCRIPTION
**Pull request by anbraten**

### CODE REVIEW

**Comment by 6543** [comment]
@anbraten what error do you get?

**Comment by anbraten** [comment]
Sth about build tags are configured twice.

**Comment by 6543** [comment]
could you provide logs or an screenshot ...

**Comment by anbraten** [comment]
image

image

As the docs state this option is basically not needed as "go.buildTags" is already set.

**Review by 6543 — APPROVED** [review]

**Comment by 6543** [comment]
must be my IDE who is in the broken state then ...

**Review by lafriks — APPROVED** [review]

**Pull request merged**
