### PR TITLE
Add godot linter to harmonitze toplevel comments

### PR DESCRIPTION
**Pull request by xoxys**
I would like to harmonize at least top level comments in the code. I have not yet applied any code changes, please review the settings and let me know which style you prefer.

### CODE REVIEW

**Comment by xoxys** [comment]
@woodpecker-ci/maintainers Please add your opinions, otherwise Ill use the current config and apply the required changes.

**Comment by 6543** [comment]
hmm even you told to ignore cSpell - the linter errors :/

**Comment by xoxys** [comment]
For now that doesn't really matter IMO. Ill address this as soon as I start to work on the refactoring.

**Comment by xoxys** [comment]
Fixed the exclude config just to proof it works. Pretty sure there will be more as soon as I start to work on it.

**Review by pat-s — APPROVED** [review]

**Review by 6543 — APPROVED** [review]

**Pull request merged**
