### PR TITLE
Use icons for step and workflow states

### LINKED ISSUE #1393: Help color blind people by changing dots to icons
### Clear and concise description of the problem

As a colorblind user, it is difficult for me to see the status of steps in pipelines.

### Suggested solution

Change the colored dot in the web-ui over to an icon. We could possibly reuse the icons used to display the status in the workflow view.

The colored dot in question:
image

This is the icon I think we could use (of course "all of them" depending on status).
image

### Alternative

Other icons or leave it be? It's not a huge inconvenience (though I'm not fully colorblind)

### Additional context

_No response_

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.

### PR DESCRIPTION
**Pull request by anbraten**
close #1393

| Old icons | New icons | New icons without colors (colorblind) |
|---|---|---|
| image | image | image |

image

# Changes
- [x] use icons for workflows and steps #1393
- [x] do not collapse failed workflows
- [x] simplify icons and their coloring #959
- [x] add popover / title to status so you can see the string version on hover
- [x] scroll workflow list #1328

### CODE REVIEW

**Comment by anbraten** [comment]
List of all current icons:

image

Linking #959

**Comment by anbraten** [comment]
Maybe as simplified new icon collections this:

image

**Comment by anbraten** [comment]
@gapodo What do you think about the icons?

**Comment by gapodo** [comment]
IMHO this looks great (and even makes sense in completely momochrome, which would be the most extreme form, can't really judge on that, since I am only reed green blind).

But having the icons is a huge improvement to me!

Thanks for implementing it

**Comment by anbraten** [comment]
@gapodo Good catch. We definitely have to use the same colors for the icons and bars. It may even help in this case, but I guess we should not rely on that contrast as its pretty hard to maintain.

**Comment by 6543** [comment]
is there a new animation for running?

**Comment by anbraten** [comment]
I have currently removed the animation (the rotating blue dots, the pecking woodpecker for sure not 😉). Not sure about it yet. For the workflows / steps list it was quite a lot.

**Review by 6543 — APPROVED** [review]

**Pull request merged**
