### PR TITLE
Update docs npm deps non-major

### PR DESCRIPTION
**Pull request by pat-s**
To fix security scan issues of `axios`. (renovate would have only scheduled this tomorrow or on Sunday). I force-triggered the creation.

Usually renovate would also create the PR but it was somehow stuck between automerge and missing branch tests (which is also why #2798 is good to have).

### CODE REVIEW

**Comment by pat-s** [comment]
Ah we need a major bump :/

**Comment by lafriks** [comment]
looks like related `Broken lockfile: no entry for '/wait-on/7.1.0(debug@4.3.4)' in pnpm-lock.yaml`

**Comment by pat-s** [comment]
Yes, but we need to wait for https://github.com/jeffbski/wait-on/issues/143 anyhow. It should then resolve itself.

**Review by 6543 — APPROVED** [review]

**Comment by pat-s** [comment]
Why merge? The issue I links above is still open and actually required?

**Comment by 6543** [comment]
the usual bump worked - only the sec fix did not went in, I think that can be done in a dedicated pull

**Pull request merged**
