### PR TITLE
Use unified rounded corners for all elements in the nav bar

### PR DESCRIPTION
**Pull request by xoxys**
Nav bar:
Bildschirmfoto vom 2023-07-15 13-43-18
image
image

Other icon buttons:
Bildschirmfoto vom 2023-07-15 13-50-18

### CODE REVIEW

**Comment by 6543** [comment]
https://github.com/woodpecker-ci/woodpecker/pull/1350

**Review by 6543 — CHANGES_REQUESTED** [review]
we need to find a solution to let the other elements als be somewhat square with rounded corners ... and not the other way around

**Comment by 6543** [comment]
PS: i agrre it should be unified but not in circles :)

**Comment by xoxys** [comment]
Sorry, I'm somehow not that successful in finding existing problems/decisions with the GH search 🙈

**Comment by 6543** [comment]
No problem, Ill just point them out if they exist ... I'm also not the best in that :)

**Review by 6543 — APPROVED** [review]

**Pull request merged**
