### PR TITLE
Remove discord as official community channel

### PR DESCRIPTION
**Pull request by 6543**
as we mostly already stop-ed using discord, we should not encourage to new users

### CODE REVIEW

**Comment by 6543** [comment]
well i would first start with just make it unofficial ...

**Comment by anbraten** [comment]
I would just leave the general channel. Seems like some users still use it and help each other.

**Review by lafriks — APPROVED** [review]

**Review by pat-s — APPROVED** [review]

**Comment by 6543** [comment]
> I would just leave the general channel. Seems like some users still use it and help each other, so why should we force them to use matrix.

I think we should not force - the discord server is still able to be discovered via discord and I wont delete the server - e.g. it's now just unofficial but we can & still should have a look at it from time to time

**Comment by 6543** [comment]
I dont see harm in having release notes there ... untill it breaks at that point we can remove it

**Comment by 6543** [comment]
ok could you submit a pull to rm it then?

**Pull request merged**
