### PR TITLE
Move "skip ci" logic into global pipeline conditions

### PR DESCRIPTION
**Pull request by 6543**
... and make custom errors follow std err conventions

this fix a 500 response if the whole pipeline is filtered out

### CODE REVIEW

**Review by lafriks — APPROVED** [review]

**Comment by 6543** [comment]
hook gets ignored ... but it does not return a 204 to the webhook as expected ... need to have a look at it again :/

**Comment by 6543** [comment]
fixed and found a bug that has to be backported 😅

**Comment by 6543** [comment]
bugfix part was backported at  #2230

**Comment by 6543** [comment]
@lafriks rerequested review because of to much changes :S

**Review by lafriks — APPROVED** [review]

**Comment by xoxys** [comment]
@6543 this seems to be broken now? https://ci.thegeeklab.de/repos/13/pipeline/14

**Pull request merged**
