### PR TITLE
Add more golangci-lint linters & sort them

### LINKED ISSUE #435: Add golangci-lint
> That's a think golangci-lint suggests as well, right? Maybe we should add it?

I'm not sure if it checks filenames, but it does check package/struct names. 
Either way, I agree with adding it. It has some good linters (and some bad ones) which can be useful.

_Originally posted by @jolheiser in https://github.com/woodpecker-ci/woodpecker/issues/434#issuecomment-941292203_

### PR DESCRIPTION
**Pull request by lukashass**
Closes #435 

## TODO

- [x] fix errors
    - [x] deadcode
    - [x] errcheck
    - [x] gofmt
    - [x] goimports
    - [x] gosimple
    - [x] govet
    - [x] ineffassign
    - [x] misspell
    - [x] revive
    - [x] staticcheck
    - [x] structcheck
    - [x] typecheck
    - [x] unused
    - [x] varcheck
    - [x] whitespace
- [ ] add more linters?

### CODE REVIEW

**Comment by 6543** [comment]
I think we can let it open and merge master into this feature branch until it passes :)

**Comment by lukashass** [comment]
Should we maybe merge only `.golangci.yml` without any enforcement in CI first?
That would enable editor integrations of golangci-lint and thus assist with fixes and also somewhat prevent introducing new issues.

**Comment by lukashass** [comment]
I opened #502 which can be merged sooner since there are only passing linters included. We can then add linters one by one.

**Comment by 6543** [comment]
@lukashass resolved conflicts for you - now we can fix one by one liter issue :)

**Comment by 6543** [comment]
@lukashass hardest parts are now done - would you like to pick up the rest?

**Comment by lukashass** [comment]
Sure :wink:

**Review by 6543 — APPROVED** [review]

**Pull request merged**
