### PR TITLE
Fix Bitbucket Server branches

### LINKED ISSUE #1695: Bitbucket Server / Data Center: List branches endpoint 404
### Component

server

### Describe the bug

Hi,

I'm currently in the process of migrating a fairly old Bitbucket Server 7.x (non-cloud) instance to Bitbucket Data Center 8.8. As part of this, I'm also investigating migration of a super old woodpecker instance (`v0.8.105`) to `v0.15.7` and now to `next`.

Apart from the typical to be expected DB migrations and breaking `ENV` configuration changes, the branch list integration introduced with #907  (more exactly the `<base>/2.0/repositories/<owner>/<name>/refs/branches` template string [here](https://github.com/woodpecker-ci/woodpecker/pull/907/files#diff-ecc104bf0e9c2d9167c43bce82421e93507f8a8660f061ac2171d298dfe214ea)) is actually something still blocking us currently. It `404`s on Bitbucket Server / Data Center and consequently `500` within Woodpecker.

AFAIK for both Bitbucket Server / Data Center 7.x and 8.x (non-cloud) the proper integration endpoint should be `GET <base>/rest/api/latest/projects/<owner>/repos/<name>/branches`. Sample Bitbucket Response of this endpoint is:

```json
{
    "size": 4,
    "limit": 25,
    "isLastPage": true,
    "values": [
        {
            "id": "refs/heads/dev",
            "displayId": "dev",
            "type": "BRANCH",
            "latestCommit": "<SHA>",
            "latestChangeset": "<SHA>",
            "isDefault": false
        },
        {
            "id": "refs/heads/main",
            "displayId": "main",
            "type": "BRANCH",
            "latestCommit": "<SHA>",
            "latestChangeset": "<SHA>",
            "isDefault": true
        }
    ],
    "start": 0
}
```

Sources:
* https://developer.atlassian.com/server/bitbucket/rest/v808/api-group-repository/#api-api-latest-projects-projectkey-repos-repositoryslug-branches-get

### System Info

```shell
woodpeckerci/woodpecker-server:next-e408c1ba27-alpine
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"next-e408c1ba"}
```

### Additional context

Woodpecker Server Log:
```json
{
    "level": "error",
    "error": "Error #01: invalid character '<' looking for beginning of value\n",
    "ip": "xxx.xxx.xxx.xxx",
    "latency": 54.356947,
    "method": "GET",
    "path": "/api/repos/PROJECT/REPO/branches",
    "status": 500,
    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36",
    "time": "2023-04-03T15:57:01Z",
    "caller": "/woodpecker/src/github.com/woodpecker-ci/woodpecker/server/router/middleware/logger.go:43"
}
```

Browser Console / UI:
Bildschirm­foto 2023-04-03 um 17 57 28
Bildschirm­foto 2023-04-03 um 18 00 10

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

### PR DESCRIPTION
**Pull request by qwerty287**
Closes #1695

:warning: untested. I don't have access to a Bitbucket server

### CODE REVIEW

**Comment by 6543** [comment]
@majodev could you check if it works, this pull do publishva test tag you can pull from dockerhub

**Comment by 6543** [comment]
tag is `pull_1698`

**Comment by 6543** [comment]
@qwerty287 can you at the json from the issue as fixture to add tests for parsing

**Comment by majodev** [comment]
Can confirm getting branches from Bitbucket Server / Data Center works with `woodpeckerci/woodpecker-server:pull_1698`.

One Gotcha: 
* Output is currently limited to `25` branches (default applied if query parameter `?limit` is not specified, [see here](https://developer.atlassian.com/server/bitbucket/rest/v808/api-group-repository/#api-api-latest-projects-projectkey-repos-repositoryslug-branches-get)).
* This would either 
  * looping through all returned pages (`?limit=0` does not work for simply getting all, would just returning one entry)
  * or as a hacky workaround, you could pass `?limit=1000` (max limit allowed).

**Review by 6543 — APPROVED** [review]

**Pull request merged**
