### PR TITLE
pin xgo image

### PR DESCRIPTION
**Pull request by 6543**
similar to #4287

### CODE REVIEW

**Comment by 6543** [comment]
-> let the ci run on pull is pointless to test it ... -> merged -> proven to work by release branch

**Comment by pat-s** [comment]
This broke the renovate config for xgo: https://github.com/woodpecker-ci/woodpecker/blob/bf5405b6cc67d13e303d59abe8723ba9a8084739/.github/renovate.json#L67

**Comment by 6543** [comment]
well I wana revert it anyway (beside the docker.io prefix) if it got fixed upstream :)

**Comment by 6543** [comment]
-> https://github.com/woodpecker-ci/woodpecker/pull/4335

**Pull request merged**
