### PR TITLE
Do not alter secret key upper-/lowercase

### PR DESCRIPTION
**Pull request by qwerty287**
Don't lowercase secret names and don't uppercase env vars.

Examples:

We have a secret `SECRET_UPPER` (it will show up exactly like this in UI).

- ```yaml
  from_secret: secret_upper
  ```
  
  Matching with `from_secret` is case-insensitive, this injects `SECRET_UPPER`.
- ```yaml
  secrets: [secret_upper]
  ```
  
  Matching these secrets is case-insensitive. The env var however looks exactly like the string here. In this example, `SECRET_UPPER` is injected as `secret_upper` env.
- ```yaml
  secrets:
    - source: secret_upper
      target: some_different_name
  ```
  
  Here `SECRET_UPPER` is injected as `some_different_name`, it is not uppercased.

Closes https://github.com/woodpecker-ci/woodpecker/issues/2368
Closes https://github.com/woodpecker-ci/woodpecker/issues/3290
Closes https://github.com/woodpecker-ci/woodpecker/issues/3096

### CODE REVIEW

**Comment by 6543** [comment]
If some consider it a gug or not ... it was intended as feature initialy ... to have keys upercase everywhere ...

**Comment by 6543** [comment]
To make it non breaking we just have to add a db migration final adjusting the values in DB and in upcomming versions including this patchset the user then can decide.

Please have a look at the docs again or are you sure you catched all places mentioning secrets?

**Comment by 6543** [comment]
no it just imitated what settings do for plugins. and try to guide the user so they do get it more often right. but if we completely get rid of the automatism, I'm fine with it too.  just mind the migration ;)

**Comment by lafriks** [comment]
I'm not sure I like this change :/

**Comment by 6543** [comment]
If we encourage #3406  we can let it stay all uppercase or lowecase.

As you still kan have any key:

Environment:
  aNYkEy:
    from_secret: anykey

**Comment by 6543** [comment]
E.g. we should make it case insensitive to users :)

**Comment by xoxys** [comment]
It's not only a debugging issue. There are cases where env vars cases matters. One example is Terraform/OpenTofu, see https://opentofu.org/docs/language/values/variables/#environment-variables

That means `TF_VAR_image_id=ami-abc123` is case-sensitive and there is currently no way to set such an env var from a secret.

**Review by xoxys — APPROVED** [review]

**Comment by lafriks** [comment]
Why not set both uppercase and unchanged case env vars?

**Comment by xoxys** [comment]
> Why not set both uppercase and unchanged case env vars?

https://github.com/woodpecker-ci/woodpecker/pull/3375#issuecomment-1949913789

**Comment by lafriks** [comment]
just personal preference, not deal breaker 😉

**Pull request merged**
