### PR TITLE
Move skip-ci back into central place

### PR DESCRIPTION
**Pull request by anbraten**
The skip logic should be in a central place and not in the compiler as it also needs to work independent of the compiler.

reverts #2216

solves #2313

### CODE REVIEW

**Comment by anbraten** [comment]
> How does this solve #2313?

Yeah not directly, but it allows to use `[skip ci]` again without even having a config file present.

> In the past, I was able to work around this issue by adding [skip ci] to all commits to branches without a CI config. This is now also broken, see https://github.com/woodpecker-ci/woodpecker/pull/2216.

**Comment by xoxys** [comment]
Still not happy with this approach and a bit strange this got merged within hours while others were blocked form months... However at leadt one way back to skip ci...

**Comment by 6543** [comment]
I considder this a hotfix!!!

**Comment by 6543** [comment]
a.k.a. workaround!

**Comment by anbraten** [comment]
> I considder this a hotfix!!!

It should stay in the current place. The code is independent of the config-compiler and should work with every compiler we implement in the future.

**Pull request merged**
