### PR TITLE
Make exec run be detected as WoodpeckerCI

### PR DESCRIPTION
**Pull request by 6543**
and exclude docs/docs/40-cli.md from git as it will be generated by CI

e.g. checkout to https://github.com/adamdecaf/cidetails/pull/3 and exec `woodpecker-cli exec --build-event push --backend-engine docker` will fail atm

### CODE REVIEW

**Review by anbraten — APPROVED** [review]

**Comment by 6543** [comment]
if we build docs/docs/40-cli.md in pipeline anyway befor publishing, we might just exclude it from git?

**Comment by 6543** [comment]
ok will start with docs for now

**Comment by 6543** [comment]
1sec I need to update the when filter a bit

**Comment by 6543** [comment]
NOW it should be fine

**Pull request merged**
