### PR TITLE
Show yml config of pipeline in UI

### LINKED ISSUE #89: Show yaml file in the UI
https://github.com/laszlocph/woodpecker-ui/issues/6

### PR DESCRIPTION
**Pull request by anbraten**
Screenshot from 2022-01-09 01-49-26

closes #89

### CODE REVIEW

**Comment by 6543** [comment]
the new tab ui, do add to much "overhead", in my opinion

can we move the show config into a symbol like we do for repo config?

**Comment by anbraten** [comment]
I added the tabs as I had in mind to add more tabs like changed files, artifacts later, ... later.

**Comment by 6543** [comment]
I still think its a to big header:

| before | after |
|----------|--------|
| Bildschirmfoto zu 2022-01-02 15-41-49 | Bildschirmfoto zu 2022-01-02 15-42-13 |

what about a side bar & icons with mouse-hover-over description text ?

idea:
Bildschirmfoto zu 2022-01-02 15-55-31

**Comment by 6543** [comment]
do you have a better idea?

**Comment by anbraten** [comment]
> do you have a better idea?

I would like to keep the tabs idea as we already used such a way of navigating before, but I will have a look at the row containing the build details (pusher, commit hash, build time, ...) and the top row with the back arrow to minimize the header areas height.

**Comment by anbraten** [comment]
Screenshot from 2022-01-03 17-41-51

@6543 What do you think about this arrangement?

**Comment by 6543** [comment]
@anbraten way better - I would call it "slim" :)

**Review by 6543 — APPROVED** [review]

**Pull request merged**
