### PR TITLE
fix badges

### LINKED ISSUE #958: Pipeline status badge is currently borked
### Component

other

### Describe the bug

Made some changes to change the language for the pipeline status badge, and now it looks way off when displayed.

> This issue is just to track that change. Fix is almost coming.

### System Info

```shell
N/A
```

### Additional context

```shell
N/A
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

### PR DESCRIPTION
**Pull request by anbraten**
closes #958 

follow up of #955 

fix for badges to resolve overflowing issues due to new & longer text (build -> pipeline):
Screenshot from 2022-06-03 16-26-11

created with https://shields.io/

### CODE REVIEW

**Comment by 6543** [comment]
Can you do a after screenshot too

**Comment by anbraten** [comment]
https://img.shields.io/badge/pipeline-success-44CC11

**Comment by x80486** [comment]
OK, @anbraten, you went the same route. I was using `shields.io` as well. I won't create a pull request then.

By the way, I find `error` not quite descriptive visually, because of the gray color — I know that's a minor thing. Not sure if that one could be colored red as well.

**Comment by anbraten** [comment]
Yeah @x80486 there were quite some discussions about the different status namings and there colors as well. As far as I can rember failure means the pipeline failed. Error on the other hand could be a result of the agent being unable to start the step (container image not found ...) or an admin declined the step. In addition there was a discussion about the pending status color which is currently orange, but as orange normally means something like a warning it was changed to blue in some places. We may should start an RFC issue and discuss / note this again and cleanup the different places (badge, favicon, remote-status, pipeline steps in UI).

**Comment by anbraten** [comment]
linking #959

**Pull request merged**
