### PR TITLE
Update pipeline icons

### PR DESCRIPTION
**Pull request by anbraten**
image

### CODE REVIEW

**Comment by pat-s** [comment]
Can post some preview images?

**Comment by anbraten** [comment]
Updated the description.

**Review by pat-s — APPROVED** [review]
The gray color could be a bit lighter overall but this is unrelated to the icons per se.

**Comment by pat-s** [comment]
Still WIP or ready to merge?

**Comment by anbraten** [comment]
Would leave it for 2.1.0

**Comment by 6543** [comment]
please dont forget labeling :)

**Comment by xoxys** [comment]
IMO the circled icons were looking much better due to the unified shape.

**Comment by 6543** [comment]
to give `pending` a own color is a good improvement, but I agree with  @xoxys

**Review by lafriks — APPROVED** [review]

**Pull request merged**
