### PR TITLE
Fix slice unmarshaling

### LINKED ISSUE #3055: depends_on: [] doesn't enable DAG mode
### Component

server

### Describe the bug

`depends_on: []` like specified in https://github.com/woodpecker-ci/woodpecker/blob/c1a1f7c10b3c0840bad9c0b25fcd7f5ff8b0173b/.woodpecker/securityscan.yml is useless, and doesn't enable DAG mode as documented on https://woodpecker-ci.org/docs/usage/workflow-syntax#depends_on.

This is because DAG is only enabled for non-empty lists: https://github.com/woodpecker-ci/woodpecker/blob/c1a1f7c10b3c0840bad9c0b25fcd7f5ff8b0173b/pipeline/frontend/yaml/compiler/dag.go#L44-L51

### System Info

```shell
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"2.1.1"}
```

### Additional context

_No response_

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

### PR DESCRIPTION
**Pull request by anbraten**
closes #3055

### CODE REVIEW

**Comment by xoxys** [comment]
Is it really expected to run steps in parallel on empty depends_on lists? To me this is completely unintuitive.

**Comment by xoxys** [comment]
Why not just copy the behavior from drone and allow depends_on: [clone] to enable parallel mode for all steps in a workflow?

**Review by xoxys — CHANGES_REQUESTED** [review]
I really dont think this should be merged.

**Comment by anbraten** [comment]
@xoxys @qwerty287 Please have a look at the changes first! This has nothing to do with `depends_on` directly its a fix for the yaml parser. Refer to #3047 for your discussion.

**Comment by xoxys** [comment]
It might help to describe PRa better. However Ill remove my review...

**Comment by xoxys** [comment]
It might help to describe PRa better. However Ill remove my review...

**Comment by xoxys** [comment]
Looks like I cant remove a review. Approved...

**Review by xoxys — APPROVED** [review]

**Pull request merged**
