### PR TITLE
Move from "master" to "main" as fallback for default repo branches

### PR DESCRIPTION
**Pull request by 6543**
… and make it configurable

### CODE REVIEW

**Comment by anbraten** [comment]
@6543 I don't think we need to have that fallback at all. I checked gitea, github and gitlab and they all have values for the default-branch. For bitbucket I will check how we can get that value as well.

**Comment by 6543** [comment]
yes I would prefer to just relay on the forge

**Comment by 6543** [comment]
Just did not do research if forges do have a change to report it empty

**Comment by 6543** [comment]
->  #2065

**Pull request closed without merging**
