### PR TITLE
Warn if using secrets/env with plugin

### PR DESCRIPTION
**Pull request by qwerty287**
address https://github.com/woodpecker-ci/woodpecker/discussions/3959

If `secrets` is set, it's not a plugin anymore.

However, only warn about such cases, but do not fail.

This PR should be backported.

### CODE REVIEW

**Comment by lafriks** [comment]
Can we use settings with non-plugins?

**Comment by zc-devs** [comment]
> Can we use settings with non-plugins?

I vote for `No`.
Settings are for plugins; envs and secrets are prohibited.
Envs (and secrets*) are for general steps; (secrets*) settings are prohibited. * depends on #4015 resolution.

**Comment by zc-devs** [comment]
Title
> Disallow secrets for plugins

> for plugins envs and secrets are prohibited

> This pr changes it, they're no longer prohibited

I'm lost.

**Comment by zc-devs** [comment]
So, now using `settings` with `environment`, `secrets`, `commands`, `entrypoint` in plugins would rise warnings instead of errors and won't fail pipeline anymore, right? It is like deprecation? The reason behind this is we don't want to introduce breaking changes in pipeline syntax in upcoming `3.0`, right?

If `yes`, I would rename to `Deprecate general step syntax in plugins` with according record in the docs.

**Comment by zc-devs** [comment]
I would switch this PR to `release/v2.7` branch.

And for `3.0` I would keep errors and disallow secrets (hard-way with pipeline fail). Although it breaks pipeline syntax, security should get priority (definitely for major releases, for minor and patch versions it is an open question). Otherwise we would live with `not fixed security issue yet` badge for a year.

**Comment by lafriks** [comment]
> If you set `commands`, `environment` etc. on a plugin, the step is not treated as plugin internally anymore and will therefore not be given additional privileges without explicit definition (which requires the repo to be trusted). It will just be like any other step, so there isn't any security problem here.

Also secrets that are allowed only for specified images won't be allowed?

**Comment by zc-devs** [comment]
I understand that it works, and why. Thank you for explanation. 

> The reason behind this (changing to warnings) is we don't want to introduce breaking changes in pipeline syntax in upcoming 3.0, right?

Is this temporary solution? Do you try to trick the system?

**Comment by zc-devs** [comment]
I like fail-fast, strict approach, which was before.

**Comment by zc-devs** [comment]
I feel I make too much efforts to defend something, that I do not really use. It makes me tired. Probably, you too.

> Failing at commands and entrypoint is probably better 

I think so.

In the end, I just wanna highlight another thing. It is just to think (or not :) about, no need to reply.
https://github.com/woodpecker-ci/woodpecker/discussions/3959#discussion-6964412
Did the example work as plugin? I assume, yes.
Now, does it execut as plugin? I assume, no. Can it lead to some plugin unexpected behavior from a user point of view. How `janydoe` should have known about it? Can it lead to endless questions / bug reports?
That is how magic works.

**Review by 6543 — APPROVED** [review]

**Review by lafriks — APPROVED** [review]

**Pull request merged**
