### PR TITLE
Return return 404 if registry to delete do not exist

### LINKED ISSUE #524: CLI: try to delete non existing registry entry just returns not readable error
```sh
[user@PC woodpecker]$ ./dist/cli/linux_amd64/woodpecker-cli registry rm --hostname docker.io test/testCI
[user@PC woodpecker]$ ./dist/cli/linux_amd64/woodpecker-cli registry rm --hostname docker.io test/testCI
 FTL error running cli error="client error 500: Error deleting registry \"a\". sql: no rows in result set"
```
woodpecker version: d02dfe993f4cc94bd8e87f454e17bbea8eea592d

### PR DESCRIPTION
**Pull request by avinilcode**
Closes #524

### CODE REVIEW

**Comment by avinilcode** [comment]
Ok, I will keep that in mind before committing any changes, thank you for suggestion :)

**Review by 6543 — CHANGES_REQUESTED** [review]
no we have to check against the err

it could be unrelated to not found, even it it's rare

**Comment by avinilcode** [comment]
Ok

**Comment by 6543** [comment]
it's more complex? ... let me look int this today

**Comment by 6543** [comment]
(I'll push onto this pull if i find a nice solution now, else I'm ok with it)

**Comment by 6543** [comment]
I have something like this in mind ... https://github.com/go-gitea/gitea/commit/5d3dbffa150d832d2f9aedd9f90ca91178a95f9c

**Comment by avinilcode** [comment]
@6543 @qwerty287 I have made changes please review and let me know

**Comment by avinilcode** [comment]
Let me know if I have to do modifications

**Comment by 6543** [comment]
@lafriks same thought ... pushed - do refactor atm

**Review by 6543 — APPROVED** [review]

**Comment by avinilcode** [comment]
Ok, got it, can you please merge this to master.

**Pull request merged**
