### PR TITLE
Export changed files via builtin environment variables

### LINKED ISSUE #853: Add changed files env var
### Clear and concise description of the problem

There isn't a way to get the changed files of a commit/PR, which would be useful for static code checks so that they don't have to run on all files, only changed ones.

### Suggested solution

Add an environment variable that contains changed files, i.e. the list under the `Changed files` tab. To make it machine-readable, a json-style string could used. For example, [this build](https://ci.woodpecker-ci.org/woodpecker-ci/woodpecker/build/2300) would be:
```json
[".woodpecker/docs.yml"]
```

And an example with more files from a PR, https://ci.woodpecker-ci.org/woodpecker-ci/woodpecker/build/2303:

```json
["web/src/components/repo/build/BuildLog.vue","web/package.json","web/yarn.lock","web/src/components/repo/build/BuildProcList.vue","web/src/compositions/useBuildProc.ts","web/src/views/repo/build/Build.vue","web/src/views/repo/build/BuildWrapper.vue"]
```

### Alternative

I don't know if that's possible, but you could extract the build URL and then request the files from the api (if there's one).

### Additional context

I'm working on a plugin which checks files and I don't want this plugin to check all files of a repo, only changed ones.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.

### PR DESCRIPTION
**Pull request by 6543**
add **`CI_PIPELINE_FILES`** to builtin env vars

close  #853

---
*Sponsored by Kithara Software GmbH*

### CODE REVIEW

**Review by anbraten — CHANGES_REQUESTED** [review]
I wouldn't do this as the string can easily be extremely long. Getting the changed files can if needed be done using git already.

**Comment by 6543** [comment]
I'm for adding it.

first:
1. long env variables dont create any issue
2. on bigger projects this is a question of efficience (if checked via git in pipeline, it would e.g. add 9min just to checkout the whole code to get the changed files)
3. we already have the info in metadata and database anyway

**Comment by 6543** [comment]
if long env var are a concern they posibly can only make issues on windows, I can add a check for this case if desired

**Review by anbraten — COMMENTED** [review]
Still feels wrong to possibly have those super long env vars, but as it seems to be supported its fine to me.

**Comment by lafriks** [comment]
I would rather see this implemented differently than env variable, maybe having a token available for some special api call to the woodpecker server from the pipeline that would allow it to retrieve such data?

**Comment by 6543** [comment]
So basically: https://github.com/woodpecker-ci/woodpecker/discussions/2291#discussioncomment-7806713 ?

**Comment by 6543** [comment]
->  #2954

**Comment by confusedsushi** [comment]
For the user it is so convenient to just have that information. Of course he could get this information via git, or maybe later via some sort of API call. But shouldn't you make it for the user as easy as possible? You already have that information, why not forward it to the user? If the user need to bother with some git command, some HTTP API call or some other external tool he will just make mistakes.

**Comment by xoxys** [comment]
I'm also not sure about the current way of implementation. Why not use the approach from the linked issue and let e.g. plugin-git create a file that contains all changed files, one per line? The current JSON string can't be easily parsed by bash/shell.

**Comment by 6543** [comment]
well first, we do shallow clone by default.
so recover the information the server already has is just **realy** inefficient.

just to point out some numbers: big repos will rise clone time from ~3min to 12min just to get that info

**Comment by 6543** [comment]
and json can be parsed by [`jq`](https://repology.org/project/jq/versions) or `yq` witch are widely available. powershell (windows) support it natively.

**Comment by xoxys** [comment]
Ah yeah that make sense. Missed this point.

**Comment by 6543** [comment]
> I think this fixes #853?

yes it does :) - updated pull description

**Review by xoxys — APPROVED** [review]
Code LGTM.

**Pull request merged**
