### PR TITLE
Kubernetes AppArmor and seccomp

### LINKED ISSUE #2545: Support AppArmor annotations and securityContext in kubernetes backend
### Clear and concise description of the problem

I'm trying to run a container image build step in my pipeline that uses [buildah](https://quay.io/repository/buildah/stable?tab=info). I'm running into a lot of permission errors like this:

```
time="2023-10-07T19:59:26Z" level=error msg="writing \"0 0 4294967295\\n\" to /proc/17/uid_map: write /proc/17/uid_map: operation not permitted"
time="2023-10-07T19:59:26Z" level=error msg="(Unable to determine exit status)"
```

After some experimentation with podman and buildah containers on my cluster, I have determined that I need to configure a few different settings at the Pod level for this to work:

- `metadata.annotations`: I need to be able to set `container.apparmor.security.beta.kubernetes.io/<container_name>` to use a custom apparmor profile for my buildah container. I would like to use the `WOODPECKER_BACKEND_K8S_POD_ANNOTATIONS` env variable, but since the container names are randomly generated I'm not sure how to make this work.
- `spec.securityContext`: The only way I have found to make buildah work is to run it as non-root. This means that I need to set `runAsUser`, `runAsGroup`, and `fsGroup` on the Pod level `securityContext` (not the container level).

### Suggested solution

Adding support for `securityContext` seems like it should be fairly straightforward. We could just follow that same approach that is currently used for `resources`, `nodeSelector`, etc. [documented here](https://woodpecker-ci.org/docs/next/administration/backends/kubernetes#resources).

The AppArmor profile is trickier since the container name needs to be included in the annotation key. I'm imagining a configuration like `backend_options.kubernetes.appArmorProfile` that could take all of the possible values for the annotation [documented here](https://kubernetes.io/docs/tutorials/security/apparmor/). Then, the pod generation logic would just look for this configuration and add the appropriate annotation if it's found.

### Alternative

I could disable AppArmor entirely, but that's not really advisable for a production environment. I could also try to find a way to get the buildah container running as root (it should be possible), but again, that's not ideal from a security perspective.

### Additional context

This is somewhat of a follow up from #2510. I'm trying to get Woodpecker to run on my kubeadm/CRI-O based cluster running on Debian which I believe makes me some kind of leprechaun/unicorn/lochness monster. There definitely aren't many of us out there.

### Validations

- [X] Checked that the feature isn't part of the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.

### PR DESCRIPTION
**Pull request by zc-devs**
Closes #2545

seccomp
https://kubernetes.io/docs/tutorials/security/seccomp/
https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/135-seccomp/README.md

AppArmor
https://kubernetes.io/docs/tutorials/security/apparmor/
https://github.com/kubernetes/enhancements/blob/fddcbb9cbf3df39ded03bad71228265ac6e5215f/keps/sig-node/24-apparmor/README.md
Went ahead and implemented API from KEP-24 above.

### CODE REVIEW

**Comment by zc-devs** [comment]
@qwerty287 , could you build preview image?
@dominic-p, could you test then?

**Comment by dominic-p** [comment]
Wow, this is great! I was just thinking about the AppArmor issue this morning. I will test the PR images tonight and report back what I find.

**Comment by 6543** [comment]
I want to have  #3135 in first :sweat_smile: ... I think resolving conflict here is easyer

**Comment by dominic-p** [comment]
Ok, I gave this my best shot today. I can't seem to get my pipeline to run using the images for the pull request. I'm referencing the following:

- server: `pull_3123@sha256:8472964208958c0371294975476a3a7b2d931ea88cd0245fd4ed0a10c5830b32`
- agent: `pull_3123@sha256:df71f3cb5e69ead011fbe0ab2309cbee8a7e471a21702cf5ed51040528fb895e`

After I deployed those images to the cluster, I can still log in to Woodpecker, but I can no longer run pipelines. Nothing runs when I push a commit, and when I try to run one manually, I get "An unknown error occurred". I then refresh, click on the failed run and click the "Restart" button. That errors immediately. But, now I have an Errors tab which shows:

> [generic] pipeline definition not found

If I check the JS console I see a lot of 503 errors for JS and CSS as referenced below. On the server side, I see one restart for the agent Pod and none for the server. There's nothing interesting the agent logs. The server logs show a couple of errors I haven't seen before (not many though). An example is shown below.

I which I knew what was going on. If I just use the default image for the current helm chart (2.1.1) I still run into some 503 errors in the console, but I'm at least able to run pipelines. Of course, they fail because this PR isn't in place.

One other issue I'm seeing that's blocking me is the `HOME` environment variable. It looks like I need to configure that for my container to run properly, but my setting in `steps.build.environment[0]` is not being respected. The variable is still set to `/root`. Here's my full `.woodpecker.yaml` file for reference.

```
# Required to get pipelines to run at all on our cluster
# See: https://github.com/woodpecker-ci/woodpecker/issues/2510
workspace:
  base: "/woodpecker"
  path: "/"

steps:

  # We'll remove this eventually, but for now it's nice just to make sure that the most basic
  # pipeline step works
  test:
    image: public.ecr.aws/docker/library/alpine
    commands:
      - echo Hello from test

  # The real work is done here. Build and push the container image
  build:
    image: quay.io/buildah/stable:v1.33
    environment:
      # I'm not sure why, but for some reason HOME is being set to /root which breaks things
      - HOME=/home/build
    commands:
      - /bin/sh ./build.sh
    backend_options:
      kubernetes:
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 1000
          fsGroup: 1000
          apparmorProfile:
            type: Localhost
            localhostProfile: buildah
```

Questions on the above config:

1. Am I configuring the `HOME` env variable correctly?
2. Am I configuring the AppArmor profile correctly? I wasn't sure from reading the source changes for this PR.

### Server Error Log

```
2024/01/09 09:06:02 [Recovery] 2024/01/09 - 09:06:02 panic recovered:
runtime error: invalid memory address or nil pointer dereference
/usr/local/go/src/runtime/panic.go:261 (0x458ab7)
/usr/local/go/src/runtime/signal_unix.go:861 (0x458a85)
/woodpecker/src/github.com/woodpecker-ci/woodpecker/pipeline/frontend/yaml/compiler/convert.go:252 (0xe47a76)
/woodpecker/src/github.com/woodpecker-ci/woodpecker/pipeline/frontend/yaml/compiler/convert.go:131 (0xe46afa)
/woodpecker/src/github.com/woodpecker-ci/woodpecker/pipeline/frontend/yaml/compiler/compiler.go:255 (0xe44b3c)
/woodpecker/src/github.com/woodpecker-ci/woodpecker/server/pipeline/stepbuilder/stepBuilder.go:297 (0xe794fe)
/woodpecker/src/github.com/woodpecker-ci/woodpecker/server/pipeline/stepbuilder/stepBuilder.go:168 (0xe77c12)
/woodpecker/src/github.com/woodpecker-ci/woodpecker/server/pipeline/stepbuilder/stepBuilder.go:90 (0xe77407)
/woodpecker/src/github.com/woodpecker-ci/woodpecker/server/pipeline/items.go:86 (0xe93f89)
/woodpecker/src/github.com/woodpecker-ci/woodpecker/server/pipeline/create.go:81 (0xe920c5)
/woodpecker/src/github.com/woodpecker-ci/woodpecker/server/api/pipeline.go:66 (0xeb5bf5)
/woodpecker/src/github.com/woodpecker-ci/woodpecker/vendor/github.com/gin-gonic/gin/context.go:174 (0xeaaa01)
/woodpecker/src/github.com/woodpecker-ci/woodpecker/server/router/middleware/session/repo.go:191 (0xeaa87c)
/woodpecker/src/github.com/woodpecker-ci/woodpecker/vendor/github.com/gin-gonic/gin/context.go:174 (0xeaa7e1)
/woodpecker/src/github.com/woodpecker-ci/woodpecker/server/router/middleware/session/repo.go:166 (0xeaa65c)
/woodpecker/src/github.com/woodpecker-ci/woodpecker/vendor/github.com/gin-gonic/gin/context.go:174 (0xbf7d8a)
/woodpecker/src/github.com/woodpecker-ci/woodpecker/server/router/middleware/session/repo.go:157 (0xf24684)
/woodpecker/src/github.com/woodpecker-ci/woodpecker/vendor/github.com/gin-gonic/gin/context.go:174 (0xbf7d8a)
/woodpecker/src/github.com/woodpecker-ci/woodpecker/server/router/middleware/session/repo.go:71 (0xf2407d)
/woodpecker/src/github.com/woodpecker-ci/woodpecker/vendor/github.com/gin-gonic/gin/context.go:174 (0xf1cfc5)
/woodpecker/src/github.com/woodpecker-ci/woodpecker/server/router/middleware/token/token.go:32 (0xf1cfb3)
/woodpecker/src/github.com/woodpecker-ci/woodpecker/vendor/github.com/gin-gonic/gin/context.go:174 (0xbf7d8a)
/woodpecker/src/github.com/woodpecker-ci/woodpecker/server/router/middleware/session/user.go:69 (0xf25e19)
/woodpecker/src/github.com/woodpecker-ci/woodpecker/vendor/github.com/gin-gonic/gin/context.go:174 (0xbf7d8a)
/woodpecker/src/github.com/woodpecker-ci/woodpecker/server/router/middleware/store.go:29 (0x1247f53)
/woodpecker/src/github.com/woodpecker-ci/woodpecker/vendor/github.com/gin-gonic/gin/context.go:174 (0xbf7d8a)
/woodpecker/src/github.com/woodpecker-ci/woodpecker/server/router/middleware/logger.go:37 (0x1248005)
/woodpecker/src/github.com/woodpecker-ci/woodpecker/vendor/github.com/gin-gonic/gin/context.go:174 (0xf1cdd7)
/woodpecker/src/github.com/woodpecker-ci/woodpecker/server/router/middleware/header/header.go:38 (0xf1cd04)
/woodpecker/src/github.com/woodpecker-ci/woodpecker/vendor/github.com/gin-gonic/gin/context.go:174 (0xf1cc62)
/woodpecker/src/github.com/woodpecker-ci/woodpecker/server/router/middleware/header/header.go:30 (0xf1cc50)
/woodpecker/src/github.com/woodpecker-ci/woodpecker/vendor/github.com/gin-gonic/gin/context.go:174 (0xf22f47)
/woodpecker/src/github.com/woodpecker-ci/woodpecker/server/router/router.go:44 (0xf22f35)
/woodpecker/src/github.com/woodpecker-ci/woodpecker/vendor/github.com/gin-gonic/gin/context.go:174 (0xc044b9)
/woodpecker/src/github.com/woodpecker-ci/woodpecker/vendor/github.com/gin-gonic/gin/recovery.go:102 (0xc044a7)
/woodpecker/src/github.com/woodpecker-ci/woodpecker/vendor/github.com/gin-gonic/gin/context.go:174 (0xc0339a)
/woodpecker/src/github.com/woodpecker-ci/woodpecker/vendor/github.com/gin-gonic/gin/gin.go:620 (0xc0302d)
/woodpecker/src/github.com/woodpecker-ci/woodpecker/vendor/github.com/gin-gonic/gin/gin.go:576 (0xc02b5c)
/usr/local/go/src/net/http/server.go:2938 (0x8029ad)
/usr/local/go/src/net/http/server.go:2009 (0x7fe573)
/usr/local/go/src/runtime/asm_amd64.s:1650 (0x478e60)
```

### JS Console Errors

By the way, if I visit any of these asset URLs directly, they are served without issue. The problem only seems to arise when they are requested as sub-resources.

```
       GET https://example.com/assets/PipelineList-_s_Lqwn8.css 503 (Service Unavailable)
(anonymous) @ index-udtFfWJ6.js:25
ne @ index-udtFfWJ6.js:25
component @ index-udtFfWJ6.js:26
qs @ index-udtFfWJ6.js:25
(anonymous) @ index-udtFfWJ6.js:25
Promise.then (async)
S @ index-udtFfWJ6.js:25
y @ index-udtFfWJ6.js:25
A @ index-udtFfWJ6.js:25
install @ index-udtFfWJ6.js:25
use @ index-udtFfWJ6.js:1
(anonymous) @ index-udtFfWJ6.js:26
index-udtFfWJ6.js:25 Uncaught (in promise) Error: Unable to preload CSS for /assets/PipelineList-_s_Lqwn8.css
    at HTMLLinkElement.<anonymous> (index-udtFfWJ6.js:25:77767)
(anonymous) @ index-udtFfWJ6.js:25
Promise.catch (async)
ne @ index-udtFfWJ6.js:25
component @ index-udtFfWJ6.js:26
qs @ index-udtFfWJ6.js:25
(anonymous) @ index-udtFfWJ6.js:25
Promise.then (async)
S @ index-udtFfWJ6.js:25
y @ index-udtFfWJ6.js:25
A @ index-udtFfWJ6.js:25
install @ index-udtFfWJ6.js:25
use @ index-udtFfWJ6.js:1
(anonymous) @ index-udtFfWJ6.js:26
index-udtFfWJ6.js:25 
        
        
       GET https://example.com/assets/usePaginate-GItiD-La.js net::ERR_ABORTED 503 (Service Unavailable)
(anonymous) @ index-udtFfWJ6.js:25
ne @ index-udtFfWJ6.js:25
component @ index-udtFfWJ6.js:26
qs @ index-udtFfWJ6.js:25
(anonymous) @ index-udtFfWJ6.js:25
Promise.then (async)
S @ index-udtFfWJ6.js:25
y @ index-udtFfWJ6.js:25
A @ index-udtFfWJ6.js:25
install @ index-udtFfWJ6.js:25
use @ index-udtFfWJ6.js:1
(anonymous) @ index-udtFfWJ6.js:26
index-udtFfWJ6.js:25 
        
        
       GET https://example.com/assets/RepoPipelines-JY_om7Wd.js net::ERR_ABORTED 503 (Service Unavailable)
(anonymous) @ index-udtFfWJ6.js:25
ne @ index-udtFfWJ6.js:25
component @ index-udtFfWJ6.js:26
qs @ index-udtFfWJ6.js:25
(anonymous) @ index-udtFfWJ6.js:25
Promise.then (async)
S @ index-udtFfWJ6.js:25
y @ index-udtFfWJ6.js:25
A @ index-udtFfWJ6.js:25
install @ index-udtFfWJ6.js:25
use @ index-udtFfWJ6.js:1
(anonymous) @ index-udtFfWJ6.js:26
index-udtFfWJ6.js:25 
        
        
       GET https://example.com/assets/PipelineList.vue_vue_type_script_setup_true_lang--m1NbqGh.js net::ERR_ABORTED 503 (Service Unavailable)
(anonymous) @ index-udtFfWJ6.js:25
ne @ index-udtFfWJ6.js:25
component @ index-udtFfWJ6.js:26
qs @ index-udtFfWJ6.js:25
(anonymous) @ index-udtFfWJ6.js:25
Promise.then (async)
S @ index-udtFfWJ6.js:25
y @ index-udtFfWJ6.js:25
A @ index-udtFfWJ6.js:25
install @ index-udtFfWJ6.js:25
use @ index-udtFfWJ6.js:1
(anonymous) @ index-udtFfWJ6.js:26
index-udtFfWJ6.js:25 
        
        
       GET https://example.com/assets/ListItem.vue_vue_type_script_setup_true_lang-qd18oERj.js net::ERR_ABORTED 503 (Service Unavailable)
(anonymous) @ index-udtFfWJ6.js:25
ne @ index-udtFfWJ6.js:25
component @ index-udtFfWJ6.js:26
qs @ index-udtFfWJ6.js:25
(anonymous) @ index-udtFfWJ6.js:25
Promise.then (async)
S @ index-udtFfWJ6.js:25
y @ index-udtFfWJ6.js:25
A @ index-udtFfWJ6.js:25
install @ index-udtFfWJ6.js:25
use @ index-udtFfWJ6.js:1
(anonymous) @ index-udtFfWJ6.js:26
index-udtFfWJ6.js:26 
        
        
       GET https://example.com/assets/RouterView-jFcmQGvl.js net::ERR_ABORTED 503 (Service Unavailable)
(anonymous) @ index-udtFfWJ6.js:26
(anonymous) @ index-udtFfWJ6.js:25
Promise.then (async)
ne @ index-udtFfWJ6.js:25
component @ index-udtFfWJ6.js:26
qs @ index-udtFfWJ6.js:25
(anonymous) @ index-udtFfWJ6.js:25
Promise.then (async)
S @ index-udtFfWJ6.js:25
y @ index-udtFfWJ6.js:25
A @ index-udtFfWJ6.js:25
install @ index-udtFfWJ6.js:25
use @ index-udtFfWJ6.js:1
(anonymous) @ index-udtFfWJ6.js:26
index-udtFfWJ6.js:25 TypeError: Failed to fetch dynamically imported module: https://example.com/assets/RouterView-jFcmQGvl.js
M @ index-udtFfWJ6.js:25
(anonymous) @ index-udtFfWJ6.js:25
Promise.catch (async)
y @ index-udtFfWJ6.js:25
A @ index-udtFfWJ6.js:25
install @ index-udtFfWJ6.js:25
use @ index-udtFfWJ6.js:1
(anonymous) @ index-udtFfWJ6.js:26
1:20 
        
        
       GET https://example.com/api/stream/events 503 (Service Unavailable)
1:1 Uncaught (in promise) TypeError: Failed to fetch dynamically imported module: https://example.com/assets/RepoWrapper-DY9N1t88.js
```

**Comment by zc-devs** [comment]
@6543, OK, just ping me then.

**Comment by zc-devs** [comment]
> What is the correct YAML syntax for configuring an AppArmor profile using this PR?
```yaml
          apparmorProfile:
            type: Localhost
            localhostProfile: buildah
```
Your config is correct.

> Can the YAML parser be made to give more helpful feedback? 

I'm afraid, I can't answer this :(

> HOME environment variable

It sets [here](https://github.com/woodpecker-ci/woodpecker/blob/768fd71841ff348518c2988bb2d0278f59dc690e/pipeline/backend/common/script.go#L25). Seems, you cannot override it. Perhaps, [this PR](https://github.com/woodpecker-ci/woodpecker/pull/3140) addresses it.

> nil pointer dereference

Thank you for testing. I'll fix this in next couple of days.

**Comment by 6543** [comment]
@zc-devs should i resolve the conflict od do you?

**Comment by zc-devs** [comment]
I'll do it.

**Comment by zc-devs** [comment]
Pipeline
```yaml
skip_clone: true
steps:
  server:
    image: alpine
    commands:
      - echo Hello
    backend_options:
      kubernetes:
        securityContext:
          apparmorProfile:
            type: Localhost
            localhostProfile: buildah
```

Pod
```yaml
apiVersion: v1
kind: Pod
metadata:
  labels:
    step: server
  annotations:
    container.apparmor.security.beta.kubernetes.io/wp-01hkyt5x61rkxcnrrk6spwp372: localhost/buildah
spec:
  containers:
    - name: wp-01hkyt5x61rkxcnrrk6spwp372
      image: alpine

```

**Comment by dominic-p** [comment]
I was able to test the latest build of this PR, and everything seems to be working as expected! Thanks.

I haven't tested the seccomp part of this, but the AppArmor annotation is getting added correctly for me.

Of course, I'm now running into a new new issue with /dev/fuse, but I may be able to work around that in a different way. If not, I'll open an issue about adding the needed annotation for that (sigh).

**Review by 6543 — APPROVED** [review]

**Pull request merged**
