### PR TITLE
Switch to `slog`

### PR DESCRIPTION
**Pull request by qwerty287**
Use stdlib instead of zerolog.

slog misses two features from zerolog:
- `trace` level
- native error logging (I has to write a wrapper)

### CODE REVIEW

**Comment by 6543** [comment]
@qwerty287 does slog have structured logging ?

**Comment by zc-devs** [comment]
Why? What is the problem with Zerolog? What benefits does Slog bring?

**Comment by zc-devs** [comment]
First off, I'm not strictly against this. If majority is for it, then OK.

> stdlib is better than an external library

Yes, if it provides the same functionality. But there are already drawbacks. I'm afraid, that we will want some feature, that Zerolog provides, but Slog does not. Then we have to find a way again.

Also there is aspect of laziness (my :) and application stability. We use library (yes, but battle-tested and standard de-facto, IMO), we know it works great. Who knows, what pitfalls does bring other implementation? And all risks are here when there are no pros for Slog and cons/bugs/something-important of Zerolog, except Slog is in core.
Example. Suppose, we have app in Spring. Can we rework it on core Java? Yes, but for what?

Besides, I prefer Zerolog's "stream" syntax over Slog:
> log.Error().Err(err).Str("step-uuid", w.stepUUID).Msg("fail to write pipeline log to peer")
> slog.Error("fail to write pipeline log to peer", logger.Error(err), slog.String("step-uuid", w.stepUUID))

It is just my opinion. We need more voices.

**Comment by anbraten** [comment]
> Also there is aspect of laziness (my :) and application stability. 

That's a good point. So my vote can be rather treated as not against it, but also not willing to adjust it in the first place 😅

**Comment by lafriks** [comment]
I'm not strictly against it but I'm somehow sceptical :)

**Pull request closed without merging**
