### PR TITLE
Update renovate schedule & use central config repo

### PR DESCRIPTION
**Pull request by pat-s**
To reduce the `renovate` noise and relax their influence on PRs a bit, I suggest the following updates:

- Run renovate only on weekends (this should create the PRs initially)
- Automerge daily (once automerge is in place -> currently testing in helm repo). This should ideally automerge the PRs from the weekend early morning on each day. Assuming there are more than one opened on the weekend, only one can be merged each day due to required branch rebasing. Ofc automerge will only happen if tests pass.
- Use a central config repo for easier maintenance of a shared config

Central config repo: https://github.com/woodpecker-ci/renovate-config/blob/main/default.json

### CODE REVIEW

**Comment by pat-s** [comment]
The plan is to use the `renovate-approve` bot, which is already in place in the helm repo. https://github.com/apps/renovate-approve

**Comment by pat-s** [comment]
That's still an issue yes and addressed in https://github.com/woodpecker-ci/woodpecker/issues/336.

Until then it might only work for plugin repos for which no workflow approval is in place.

**Comment by pat-s** [comment]
But also besides the automerge idea, I think having renovate PR popup once per week is also "enough"? The good thing about that is that updates of the same manager are grouped usually and we don't need to deal with so many single PRs every few days.

**Review by xoxys — APPROVED** [review]
Don't know if it makes sense to enable it on this repo under these circumstances.  LGTM otherwise.

**Comment by pat-s** [comment]
Maybe it's best we add a preset config repo which hosts some presets for all repos and extend the individual configs in the repos.

Then things like `automergeDaily` would only appear there and not be explicitly present in a repo config. And we don't need so many updates in all repos.

**Comment by xoxys** [comment]
Yes, if a broader use is planned a preset repo is a better approach :+1:

**Pull request merged**
