### PR TITLE
support docker credential and add docker-credential-ecr-login into alpine image

### PR DESCRIPTION
**Pull request by xuecanlong**
## Changes
- support docker credential and add docker-credential-ecr-login into alpine image

### CODE REVIEW

**Comment by 6543** [comment]
do you have a link to what this ecr-login is?

**Comment by xuecanlong** [comment]
> * docker-credential-ecr-login

https://github.com/awslabs/amazon-ecr-credential-helper

**Comment by xuecanlong** [comment]
> do you have a link to what this ecr-login is?

https://github.com/awslabs/amazon-ecr-credential-helper

**Comment by anbraten** [comment]
I don't know if this should be part of the main container image as to be fair we would need to support Google, Azure and all the other hosters smaller ones as well. Could we add it as some kind of plugin?

**Comment by xuecanlong** [comment]
> I don't know if this should be part of the main container image as to be fair we would need to support Google, Azure and all the other hosters smaller ones as well. Could we add it as some kind of plugin?

just need add the `docker-credential-*` in system, `CredentialHelpers` is a standard. https://github.com/docker/docker-credential-helpers

**Comment by 6543** [comment]
#1075 got merged

**Pull request closed without merging**
