### PR TITLE
let remove be a remove

### LINKED ISSUE #590: Delete Repository should clean all evidence from DB
del

current behaviour: dectivate webhooks at Forge
expect:
 - deactivatewebhook at Forge
 - delete all logs, task, job ... and repo istselv from db

### PR DESCRIPTION
**Pull request by anbraten**
closes #590

### CODE REVIEW

**Comment by 6543** [comment]
last time I looked the remove did not clean db ... will check that before approving

**Comment by anbraten** [comment]
> last time I looked the remove did not clean db ... will check that before approving

Worked for me.

I added a disable button as suggested in the issue.

**Comment by 6543** [comment]
did you forgot to push - cant find the "disable" button :(

**Comment by 6543** [comment]
some obsered behaviour:
 - label `disabled` on /repos view missing
 - disabled repos ned an activation button and should hide deactivate button

**Review by 6543 — APPROVED** [review]

**Pull request merged**
