### PR TITLE
Add migration to autofix corrupted users.org_id entrys in db

### PR DESCRIPTION
**Pull request by 6543**
No idea why the corrupt entrys did exist ... we might should dig into the reason.

anyway it only happens on very old accounts and I did the migrations mannually at codeberg and now at kithara.

so we clearly should run it to catch potential hick-ups ...

### CODE REVIEW

**Comment by 6543** [comment]
might be an regression of #2126

**Comment by zc-devs** [comment]
Perhaps, related #3328

**Comment by 6543** [comment]
symptoms: you get just weard behaviour and some functions 'randomly' dont work ..

deleting all of that ward user related stuff (in db) and recreate the user by log in newly do fix it.

**Comment by pat-s** [comment]
> it only happens on very old accounts 

Define "very old" - if it happened on v1 -> v2, I'd not use that adjective here.

Also: #3319 -> can likely be closed then. Great that there is a fix now for this, a bit sad that it took almost a year. However I am not sure whether you discovered this "just recently" or were actually aware of it the whole time but it simply wasn't important enough (?).

> anyway it only happens on very old accounts and I did the migrations mannually at codeberg and now at kithara.

Hmm, just for the protocol, I did 20-30 manual corrections at CB throughout this time and was also solely commenting to user requests. Not sure which one you're referring to specifically but unless you did some in the recent days, this sounds a bit unfortunate.

**Review by pat-s — APPROVED** [review]
Assuming you tested/applied these commands on active DBs multiple times already, as stated.

**Comment by 6543** [comment]
> but unless you did some in the recent days,

On monday to be exact

**Comment by 6543** [comment]
-> #4327

**Pull request merged**
