### PR TITLE
Migrate to bun

### PR DESCRIPTION
**Pull request by anbraten**
closes #2769

### CODE REVIEW

**Comment by zc-devs** [comment]
Does it work [on Windows](https://bun.sh/blog/bun-v1.0#bun-more-thing)?

**Comment by anbraten** [comment]
> Does it work [on Windows](https://bun.sh/blog/bun-v1.0#bun-more-thing)?

Sounds like it's still experimental: https://bun.sh/docs/installation#windows

**Comment by zc-devs** [comment]
> still experimental

Perhaps, docs should be adjusted in case of WSL.

In case of native support, I'm concerned more about 

> only the JavaScript runtime is supported; the package manager, test runner, and bundler have been disabled

than performance and excessive debug logs.

P.S.: I'm not a professional in JS stuff :)

**Comment by anbraten** [comment]
replaced by #3676

**Pull request closed without merging**
