### PR TITLE
CI: add branches filter

### PR DESCRIPTION
**Pull request by 6543**

### CODE REVIEW

**Comment by 6543** [comment]
expect: exec for pull
get: 204 !

**Comment by anbraten** [comment]
similar to #1111 at least that was my intention in there as well

**Comment by 6543** [comment]
yes but this looks like it is broken ... on gitea it seems to work :O

**Comment by anbraten** [comment]
@6543 I added some `root.when` filters and replaced the `branches` filter.

**Review by anbraten — APPROVED** [review]

**Comment by 6543** [comment]
@anbraten we don't get any builds lately ... I'll revert it partially and we need a more clever solution

**Comment by 6543** [comment]
7fede8ea1dce752745ffd8c55e180e222b69dc4c

**Comment by anbraten** [comment]
@6543 Yip, saw that as well. I will try to find a solution for the root level when filters. Currently they are reporting pending state back although they are not running at all

**Pull request merged**
