### PR TITLE
 Remove old CLI docs generation code 

### PR DESCRIPTION
**Pull request by qwerty287**
Removes code that's not longer required because we use a newer version of urfave/cli.

### CODE REVIEW

**Review by 6543 — APPROVED** [review]

**Review by anbraten — APPROVED** [review]

**Review by anbraten — APPROVED** [review]

**Comment by anbraten** [comment]
Should we add this command to the ci / docs generation so it would be updated automatically? :thinking:

**Comment by anbraten** [comment]
Ahh nice.

**Comment by anbraten** [comment]
Or we make it a separate ci step

**Review by anbraten — APPROVED** [review]

**Comment by anbraten** [comment]
Strange, quite some failing pipelines recently.

**Comment by 6543** [comment]
The generated stuff could be invalid to editorconfig ... we should exclude it from tests

**Comment by 6543** [comment]
https://github.com/woodpecker-ci/woodpecker/blob/master/.ecrc

Does not include it ... if it pass then well its good :)

**Pull request merged**
