### PR TITLE
Add support to run pipelines using a local backend

### LINKED ISSUE #559: Support `local` as backend
run an agent that runs commands on the host machine

### PR DESCRIPTION
**Pull request by Ta180m**
This adds support for #559. I tested using [this .woodpecker.yml](https://git.exozy.me/Ta180m/Hello-world/src/branch/main/.woodpecker.yml) on my self-hosted [Woodpecker instance](https://ci.exozy.me/Ta180m/Hello-world). I was also able to get this to build [Hugo websites](https://ci.exozy.me/Ta180m/howtuwu/build/1). It's currently very simplistic but works!

close #559

### CODE REVIEW

**Comment by Ta180m** [comment]
I tried getting secrets to work, and it works about 50% of the time. When it fails, I think the relevant error is `"error":"rpc error: code = Unknown desc = database is locked"` but I'm not entirely sure.

**Comment by Ta180m** [comment]
I've been using this backend for about a day, and it should be pretty stable now. Secrets *should* actually work now, this gets both the Stdout and Stderr of the pipeline commands, and the "image" specifies the shell used to run the pipeline, such as `sh` or `fish`.

**Comment by mscherer** [comment]
Could you add some documentation on it ? 

At minima, it requires to be added to docs/docs/30-administration/15-agent-config.md

**Comment by mscherer** [comment]
Also, while I understand why you did that, I think the re-use of "image" mean that the .woodpecker.yml file is now silently agent and backend specific. I do not have a better proposal but I suspect it might cause issues later.

**Comment by Ta180m** [comment]
> > Could you add some documentation on it ?
> > At minima, it requires to be added to docs/docs/30-administration/15-agent-config.md
> 
> Sure, I will write some documentation. This backend requires no setup since it runs the pipelines directly, and the `.woodpecker.yml` configuration is the exact same except that `image` specifies the shell (i.e. bash, zsh) used to run the commands. Currently you need to create a custom `clone` stage, but I'll push a commit soon to fix this.

I added support to run the default clone stage with a [`plugin-git`](https://github.com/woodpecker-ci/plugin-git) binary on the `$PATH`. I'll add that to the documentation too.

**Comment by wxiaoguang** [comment]
> Also, while I understand why you did that, I think the re-use of "image" mean that the .woodpecker.yml file is now silently agent and backend specific. I do not have a better proposal but I suspect it might cause issues later.

Agree, it's not ideal to use `image: local` to switch the `backend engine`

Now, woodpecker uses `WOODPECKER_BACKEND (auto-detect/docker)` to set the default backend engine, and in code it is called engine, too.

To make these options consistent, I think a new option `engine` for pipelines.

```
pipeline:
    task-a:
        engine: default/docker
        image: ...
    task-b:
        engine: shell
        .....
```

**Comment by Ta180m** [comment]
> > Also, while I understand why you did that, I think the re-use of "image" mean that the .woodpecker.yml file is now silently agent and backend specific. I do not have a better proposal but I suspect it might cause issues later.
> 
> Agree, it's not ideal to use `image: local` to switch the `backend engine`
> 
> Now, woodpecker uses `WOODPECKER_BACKEND (auto-detect/docker)` to set the default backend engine, and in code it is called engine, too.
> 
> To make these options consistent, I think there could be a new option `engine` for pipelines.
> 
> ```
> pipeline:
>     task-a:
>         engine: default-backend / docker / ...
>         image: ...
>     task-b:
>         engine: shell
>         .....
> ```
> 
> The similiar concept in GitLab Runner is `executor`: https://docs.gitlab.com/runner/executors/

This PR doesn't use `image` to specify the backend engine, but rather the shell (bash, fish, etc) that is used to run the commands. I do agree that adding an `engine` option to pipelines is a good idea.

**Comment by wxiaoguang** [comment]
> This PR doesn't use `image` to specify the backend engine, but rather the shell (bash, fish, etc) that is used to run the commands. 

Sorry, I misunderstood the design. Please ignore the previous comment. 

But re-using `image` field seems strange, and another question is that how to mix the shell and docker agents together in one woodpecker cluster? Maybe something like this?

docker agents:
* WOODPECKER_HOSTNAME=node1.docker-agents
* WOODPECKER_HOSTNAME=node2.docker-agents
...
shell agents:
* WOODPECKER_HOSTNAME=node1.shell-agents
* WOODPECKER_HOSTNAME=node2.shell-agents
...


```
# use shell engine
when:
    hostname: *.shell-agents
pipeline:
    task-a:
        shell: bash
    task-b:
        shell: zsh
```

```
# use docker engine
when:
    hostname: *.docker-agents
pipeline:
    task-x:
        image: git
    task-y:
        image: golang
```

**Comment by Ta180m** [comment]
> > This PR doesn't use `image` to specify the backend engine, but rather the shell (bash, fish, etc) that is used to run the commands.
> 
> Sorry, I misunderstood the design. Please ignore the previous comment.
> 
> But re-using `image` field seems strange, and another question is that how to mix agents with different engines (shell/docker, etc) together in one woodpecker cluster? Maybe something like this?
> 
> docker agents:
> 
>     * WOODPECKER_HOSTNAME=node1.docker-agents
> 
>     * WOODPECKER_HOSTNAME=node2.docker-agents
>       ...
> 
> 
> shell agents:
> 
>     * WOODPECKER_HOSTNAME=node1.shell-agents
> 
>     * WOODPECKER_HOSTNAME=node2.shell-agents
>       ...
> 
> 
> ```
> # use shell engine
> when:
>     instance: *.shell-agents
>    # or add an option to choose agents?
>     engine: shell
> pipeline:
>     task-a:
>         shell: bash
>     task-b:
>         shell: zsh
> ```
> 
> ```
> # use docker engine
> when:
>     instance: *.docker-agents
>    # or add an option to choose agents?
>     engine: docker
> pipeline:
>     task-x:
>         image: git
>     task-y:
>         image: golang
> ```

I think mixing agents with different engines is outside the scope of this PR, but could be a good idea for a future PR.

As for using the `image` field for specifying the shell, it is a strange choice but also very straightforward to implement since I just had to reuse the existing `image` field. However I do think it would be a good idea to use a `shell` field as you suggested for this.

**Review by 6543 — APPROVED** [review]
ack as it doesnt interfer and can be improved later

**Comment by vanous** [comment]
Hi!

i know this backend is not the main focus.. but i am trying to make this work (i have a local binary ([of older publican](https://jfearn.fedorapeople.org/en-US/Publican/index.html))  that i either have to pack into a docker image and push that image somewhere... or just run local backend), but i am missing something...

I added `- WOODPECKER_BACKEND=local` to the agent:

```yml
  woodpecker-agent:
    image: woodpeckerci/woodpecker-agent:next
    command: agent
    restart: always
    depends_on:
      - woodpecker-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WOODPECKER_LOG_LEVEL=${WOODPECKER_LOG_LEVEL}
      - WOODPECKER_SERVER=woodpecker-server:9000
      - WOODPECKER_AGENT_SECRET=${WOODPECKER_AGENT_SECRET}
      - WOODPECKER_BACKEND=local
```
but i always get:

```
woodpecker_woodpecker-agent_1 exited with code 0
woodpecker-agent_1   | {"level":"error","error":"stat /tmp: no such file or directory","time":"2022-08-12T13:43:18Z","message":"cannot 
load backend engine"}
```
Do i need to do something special? Thank you very much!

**Comment by vanous** [comment]
OK, for those, struggling to get this working, here is a quick info, i will try to put this into the docs once time permits:

1) expose woodpecker-server's grpc:

\- 9000:9000

2) install binary on the agent machine:
- woodpecker-agent {next, as of the time of the writing}
- plugin-git

3) run the agent on the agent machine. 

`/woodpecker-agent --grpc-password $WOODPECKER_AGENT_SECRET --backend-engine local`

If the agent machine is not the same as the server, provide --server:

--server $SERVER_ADDRESS:9000

**Comment by tandav** [comment]
> 2. install binary on the agent machine:
> 
> * woodpecker-agent {next, as of the time of the writing}

@vanous can you provide a link to binary you're using.
I downloaded [woodpecker-agent_linux_amd64.tar.gz](https://github.com/woodpecker-ci/woodpecker/releases/download/v0.15.4/woodpecker-agent_linux_amd64.tar.gz) and when I run it I get

```
/woodpecker-agent --backend-engine local
{"level":"error","error":"Backend engine 'local' not found","time":"2022-09-17T17:23:55+03:00","message":"cannot find backend engine 'local'"}
```
the same error if I use `WOODPECKER_BACKEND=local` in `.env` file

**Comment by anbraten** [comment]
You have to use a backen with next version.

**Comment by tandav** [comment]
> You have to use a binary / conrainer with next version.
yes, i use following config and still have error

```yml
version: '3'

services:
  woodpecker-server:
    image: woodpeckerci/woodpecker-server:next
    ports:
      - 8000:8000
      - 9000:9000
    volumes:
      - woodpecker-server-data:/var/lib/woodpecker/
    environment:
      - WOODPECKER_OPEN=true
      - WOODPECKER_HOST=...
      - WOODPECKER_GITEA=true
      - WOODPECKER_GITEA_URL=...
      - WOODPECKER_GITEA_CLIENT=...
      - WOODPECKER_GITEA_SECRET=...
      - WOODPECKER_AGENT_SECRET=...

  woodpecker-agent:
    image: woodpeckerci/woodpecker-agent:next
    command: agent
    restart: always
    depends_on:
      - woodpecker-server
    volumes:
      - /run/user/1000/docker.sock:/var/run/docker.sock
    environment:
      - WOODPECKER_SERVER=woodpecker-server:9000
      - WOODPECKER_AGENT_SECRET=...
      - WOODPECKER_BACKEND=local

volumes:
  woodpecker-server-data:

```

**Comment by 6543** [comment]
can you please open a new issue or use our chat for debugging config issues ...
... in this case you try to use the local backend inside a container that does not have any shell!

and still mount a docker socket into it so you either wannt to run the agent bare mettal or use the docker backend

**Pull request merged**
