### PR TITLE
Add blocklist of environment variables who could alter execution of plugins

### PR DESCRIPTION
**Pull request by 6543**
close https://github.com/woodpecker-ci/woodpecker/issues/3929

reviewed at https://github.com/woodpecker-ci/woodpecker-security/pull/15

### CODE REVIEW

**Comment by MagicRB** [comment]
The history of this PR is unclear. It was commited 6 hours ago and yet is in a released version of buildbot already. (As of writing this the CI hasn't even finished running). Can someone please clarify what's the purpose of this fix, why is it needed?

**Comment by reddec** [comment]
@6543 While I can understand the changes, I am pretty confused by the discussion that was done behind closed doors: https://github.com/woodpecker-ci/woodpecker-security is a closed repo. Also, I couldn't find any approvals or reviewers for the PR.

**Comment by MagicRB** [comment]
I didn't have time to look it over because I am just leaving the gym, but I did get an explanation from an aquaintance and it makes sense, I'll repost here if they allow. But yeah the way this was merged in is very dubious.

**Comment by 6543** [comment]
> The history of this PR is unclear. It was commited 6 hours ago and yet is in a released version of buildbot already. (As of writing this the CI hasn't even finished running). Can someone please clarify what's the purpose of this fix, why is it needed?

Sorry but we dont want bad acktory to atack users!

So we work serious security fixes in private, when time has passed all the information will be released. For now you can read the patch itselve and guess what to do.

**Pull request merged**
