### PR TITLE
Add release helper

### PR DESCRIPTION
**Pull request by anbraten**

### CODE REVIEW

**Comment by 6543** [comment]
we already have https://github.com/woodpecker-ci/woodpecker/pull/1854 ?

**Comment by anbraten** [comment]
Sample release PR: https://github.com/anbraten/test-ready-release-go/pull/52
As you can see in there each time a PR was merged into `main` the plugin go executed and updated the release PR.
If you want to release a new version you can simply review the PR and merge it, which will merge the updated / reviewed changelog etc. After the release-PR got merged the plugin will be triggered again creating a tag & release.

**Comment by 6543** [comment]
can we let it ignore commits with no assigned pull?

**Review by pat-s — APPROVED** [review]

**Comment by pat-s** [comment]
@anbraten Just in case 

https://ci.woodpecker-ci.org/repos/3780/pipeline/7649/17#L812

needs 

image

**Pull request merged**
