### PR TITLE
Fix codecov plugin version

### PR DESCRIPTION
**Pull request by pat-s**
After the recent update of the plugin (which now follows semver)

### CODE REVIEW

**Comment by pat-s** [comment]
Hmm seems like there's something wrong with the arch in the image :/

**Review by anbraten — APPROVED** [review]

**Comment by pat-s** [comment]
No wait, the test actually failed but it was not reflected in the CI run...

```
$ /bin/codecov -Q woodpecker --rootDir /woodpecker/src/github.com/woodpecker-ci/woodpecker --nonZero --file agent-coverage.out --file cli-coverage.out --file coverage.out --file server-coverage.out --file datastore-coverage.out
[2](https://ci.woodpecker-ci.org/repos/3780/pipeline/9004/26#L2)023/10/24 12:46:39 fork/exec /bin/codecov: exec format error
```

**Comment by pat-s** [comment]
https://ci.woodpecker-ci.org/repos/3780/pipeline/9004/26

**Comment by pat-s** [comment]
because of ` failure: ignore`

**Comment by pat-s** [comment]
https://github.com/woodpecker-ci/plugin-codecov/pull/13

**Pull request merged**
