### PR TITLE
Use fix width for pipeline step list

### PR DESCRIPTION
**Pull request by xoxys**
On larger monitors using dynamic width in percent, the step list can become very wide which makes it hard to read.

### CODE REVIEW

**Comment by 6543** [comment]
could you provide some screenshots :)

**Comment by xoxys** [comment]
Sorry, of course:

image
image

**Review by 6543 — APPROVED** [review]

**Review by 6543 — APPROVED** [review]

**Review by anbraten — COMMENTED** [review]
Wouldn't it be better to use a max width here

**Comment by xoxys** [comment]
> Wouldn't it be better to use a max width here

Yep, will create a follow-up PR.

**Pull request merged**
